SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Ano_analisis__c</fullName>
        <label>Año análisis</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad__c</fullName>
        <label>Ciudad</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Codigo_postal__c</fullName>
        <label>Código postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Precio_HD_Grado_1__c</fullName>
        <label>Precio HD Grado 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Precio_HD_Grado_2__c</fullName>
        <label>Precio HD Grado 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Precio_HD_Grado_3__c</fullName>
        <label>Precio HD Grado 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Precio_HI_Grado_1__c</fullName>
        <label>Precio HI Grado 1</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Precio_HI_Grado_2__c</fullName>
        <label>Precio HI Grado 2</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Precio_HI_Grado_3__c</fullName>
        <label>Precio HI Grado 3</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Provincia__c</fullName>
        <label>Provincia</label>
        <picklist>
            <picklistValues>
                <fullName>A Coruña</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alacant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Álava</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albacete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Almería</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asturias</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ávila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Badajoz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bizkaia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burgos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cáceres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cádiz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cantabria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Castelló</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceuta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ciudad Real</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Córdoba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuenca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gipuzkoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Girona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guadalajara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huelva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huesca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illes Balears</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaén</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>La Rioja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Las Palmas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>León</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_analisis__c</fullName>
        <label>Tipo análisis</label>
        <picklist>
            <picklistValues>
                <fullName>Febrero</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Octubre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Servicio__c.object
<CustomObject>
    <fields>
        <fullName>Grado_Dependencia__c</fullName>
        <label>Grado Dependencia</label>
        <picklist>
            <picklistValues>
                <fullName>Grado 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grado 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grado 3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Servicio__c</fullName>
        <label>Servicio</label>
        <picklist>
            <picklistValues>
                <fullName>TAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixto</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Estancia__c</fullName>
        <label>Tipo Estancia</label>
        <picklist>
            <picklistValues>
                <fullName>Permanente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Ocupacion__c</fullName>
        <label>Tipo Ocupación</label>
        <picklist>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI Baño Compartido</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD Uso Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jornada Completa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Jornada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 hora</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 horas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 horas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 horas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 horas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 horas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fisio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psicología</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terapia Ocupacional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Animación Sociocultural</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Servicio__c</fullName>
        <label>Tipo Servicio</label>
        <picklist>
            <picklistValues>
                <fullName>Centro de Día</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro de Noche</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convalecencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fijo Discontinuo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital de Día</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paliativo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residencial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respiro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UTC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apartamento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sociosanitario Privado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arrend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arrend viv y servicio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apartamento social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rehabilitación psicosocial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servicios Externos</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Servicio</label>
    <nameField>
        <label>Nombre de Servicio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicios</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/tgTarifasTOcCTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class tgTarifasTOcCTest {

    static testMethod void myUnitTest() {
    	
    	Servicio__c sc1 = new Servicio__c();
    	sc1.Name = 'sc1';
    	sc1.Tipo_Servicio__c = 'Residencial';
    	sc1.Tipo_Estancia__c = 'Permanente';
    	sc1.Tipo_Ocupacion__c = 'HD';
    	sc1.Grado_Dependencia__c = 'Grado 1';
    	insert sc1;
    	
    	Servicio__c sc2 = new Servicio__c();
      	sc2.Name = 'sc2';
    	sc2.Tipo_Servicio__c = 'Residencial';
    	sc2.Tipo_Estancia__c = 'Permanente';
    	sc2.Tipo_Ocupacion__c = 'HD';
    	sc2.Grado_Dependencia__c = 'Grado 2';
    	insert sc2;
    	
    	Servicio__c sc3 = new Servicio__c();
      	sc3.Name = 'sc3';
    	sc3.Tipo_Servicio__c = 'Residencial';
    	sc3.Tipo_Estancia__c = 'Permanente';
    	sc3.Tipo_Ocupacion__c = 'HD';
    	sc3.Grado_Dependencia__c = 'Grado 3';
    	insert sc3;
    	
    	Servicio__c sc4 = new Servicio__c();
       	sc4.Name = 'sc4';
    	sc4.Tipo_Servicio__c = 'Residencial';
    	sc4.Tipo_Estancia__c = 'Permanente';
    	sc4.Tipo_Ocupacion__c = 'HI';
    	sc4.Grado_Dependencia__c = 'Grado 1';
    	insert sc4;
    	
    	Servicio__c sc5 = new Servicio__c();
       	sc5.Name = 'sc5';
    	sc5.Tipo_Servicio__c = 'Residencial';
    	sc5.Tipo_Estancia__c = 'Permanente';
    	sc5.Tipo_Ocupacion__c = 'HI';
    	sc5.Grado_Dependencia__c = 'Grado 2';
    	insert sc5;
    	
    	Servicio__c sc6 = new Servicio__c();
    	sc6.Name = 'sc6';
    	sc6.Tipo_Servicio__c = 'Residencial';
    	sc6.Tipo_Estancia__c = 'Permanente';
    	sc6.Tipo_Ocupacion__c = 'HI';
    	sc6.Grado_Dependencia__c = 'Grado 3';
    	insert sc6;
    	
        Account com1 = new Account();
        com1.RecordTypeId = '012b0000000QC89AAG';
        com1.Name = 'com1';
        //com1.PersonEmail = 'test@test.com';
        com1.Phone = '4441556454';
        com1.Calle__c = 'Carrer valencia 20';
        com1.Ciudad__c = 'Barcelona';
        com1.Codigo_postal__c = '08505';
        com1.Provincia__c = 'Barcelona';
        com1.Tipo_analisis__c = 'Febrero';
	    com1.Ano_analisis__c = '2010';
	    com1.Precio_HD_Grado_1__c = 25.50;
		com1.Precio_HD_Grado_2__c = 90.50;
		com1.Precio_HD_Grado_3__c = 150.50;
		com1.Precio_HI_Grado_1__c = 22.00;
		com1.Precio_HI_Grado_2__c = 80.00;
		com1.Precio_HI_Grado_3__c = 100.00;
        insert com1;
    }
}