SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Director_del_centro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio si el centro está Activo</inlineHelpText>
        <label>Director del centro</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Director Centro</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Director_centro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>División</label>
        <picklist>
            <picklistValues>
                <fullName>Residencial</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Adorea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAR Domus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domiciliaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IdNAV__c</fullName>
        <description>Identificador de Navision</description>
        <externalId>true</externalId>
        <label>IdNAV</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Residencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zona_Comercial_del__c</fullName>
        <label>Zona Comercial Centro</label>
        <picklist>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Este</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mallorca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navarra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oeste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Occidental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Oriental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zaragoza</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Centro</fullName>
        <active>true</active>
        <description>Residencias</description>
        <label>Centro</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Centros_NOC__c.object
<CustomObject>
    <description>Centros que comparten una misma NOC</description>
    <fields>
        <fullName>Activo__c</fullName>
        <label>Activo</label>
        <picklist>
            <picklistValues>
                <fullName>Si</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Descuento__c</fullName>
        <label>Descuento</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>División</label>
        <picklist>
            <picklistValues>
                <fullName>Residencial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adorea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAR Domus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domiciliaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEX</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Grado__c</fullName>
        <label>Grado</label>
        <picklist>
            <picklistValues>
                <fullName>Grado 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grado 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grado 3</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>NOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOC</label>
        <referenceTo>NOC__c</referenceTo>
        <relationshipLabel>Centros / Servicios NOCs Residencial</relationshipLabel>
        <relationshipName>Centros_NOCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tipo_Estancia_2__c</fullName>
        <label>Tipo Estancia</label>
        <picklist>
            <picklistValues>
                <fullName>Permanente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporal</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Ocupacion_2__c</fullName>
        <label>Tipo Ocupación</label>
        <picklist>
            <picklistValues>
                <fullName>HD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI Baño Compartido</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HD Uso Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jornada Completa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Media Jornada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 hora</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 horas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 horas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 horas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 horas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 horas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fisio</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Servicio_2__c</fullName>
        <label>Tipo Servicio</label>
        <picklist>
            <picklistValues>
                <fullName>Centro de Día</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro de Noche</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convalecencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fijo Discontinuo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital de Día</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paleativo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residencial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respiro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UTC</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Centros/Servicios NOC</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Centros NOC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Centros NOCs</pluralLabel>
    <recordTypes>
        <fullName>Centros_Servicios_NOC_mejorada</fullName>
        <active>true</active>
        <label>Centros/Servicios NOC (mejorada)</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/NOC__c.object
<CustomObject>
    <fields>
        <fullName>Descuento__c</fullName>
        <formula>1-(Precio_propuesto__c  /   Precio_actual__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Descuento</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>División</label>
        <picklist>
            <picklistValues>
                <fullName>Residencial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adorea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAR Domus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domiciliaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Duracion_del_descuento__c</fullName>
        <inlineHelpText>Sólo para la división Residencial</inlineHelpText>
        <label>Duración del descuento en días</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estado_Flujo__c</fullName>
        <label>Estado Flujo</label>
        <picklist>
            <picklistValues>
                <fullName>Pendiente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aprobado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fecha_fin__c</fullName>
        <inlineHelpText>Periodo en el que puede utilizarse la NOC</inlineHelpText>
        <label>Fecha fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fecha_inicio__c</fullName>
        <inlineHelpText>Periodo en el que puede utilizarse la NOC</inlineHelpText>
        <label>Fecha inicio</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grado__c</fullName>
        <formula>IF( RecordType.DeveloperName=&apos;NOC_11_Descuento_Personal_Renegociado&apos;,TEXT( Oportunidad_renegociada__r.Servicio__r.Grado_Dependencia__c) ,  TEXT( Oportunidad__r.Servicio__r.Grado_Dependencia__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grado</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id_contrato__c</fullName>
        <label>Id contrato</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Visibilidad_Centros_1__c</fullName>
        <label>Visibilidad Centros 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NOC</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NOCs</pluralLabel>
    <recordTypes>
        <fullName>NOC_9_Campana</fullName>
        <active>true</active>
        <description>Comunicaciones, presentaciones y campañas</description>
        <label>NOC 9 Comunicaciones, presentaciones y campañas</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/TestTgNocAprobada.cls
/** 
* File Name:   TestTgNocRechazada 
* Description: Test del trigger TgNocAprobada
* Copyright:   Konozca 
* @author:     Hector Mañosas
* Modification Log 
* =============================================================== 
*Date     Author           Modification 
* 11/10/2014
* =============================================================== 
**/ 
@isTest
private class TestTgNocAprobada {

    static testMethod void myUnitTest() {
    	
    	RecordType rtn = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'NOC_9_Campana'];
    	RecordType rc = [SELECT Id, Name, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Centros_Servicios_NOC_mejorada' LIMIT 1];
    	
    	//Insert NOC    	
        NOC__c testIS = new NOC__c();
        testIS.RecordTypeId = rtn.Id;
        testIS.Estado_Flujo__c = 'Pendiente';        
        testIS.Fecha_inicio__c = System.today().addDays(-30);
        testIS.Fecha_fin__c = System.today().addDays(15);
        testIs.Visibilidad_Centros_1__c = 'CANBUXERES';
        testIS.Duracion_del_descuento__c = 10;
        //testIS.Id_contrato__c = 'CTR00001';
        testIS.Residencial__c = true;
        triggerHelper.recursiveHelper3(true);        
        insert testIS;
        triggerHelper.recursiveHelper3(false);
        
        //Creamos una Account de tipo Centro
        Account centro1 = new Account();
        centro1.Name = 'Can Buxeres';
        centro1.RecordTypeId = '012b0000000QAeAAAW';        
        centro1.Phone = '442342343244';
        centro1.Activo__c = true;
        centro1.Director_del_centro__c = '005b0000000kj7HAAQ';
        centro1.Division__c = 'Residencial';
        centro1.Zona_Comercial_del__c = 'Barcelona';
        centro1.IdNAV__c = 'CANBUXERES';
        triggerHelper.recursiveHelper3(true);
        insert centro1;
        triggerHelper.recursiveHelper3(false);
        
        //Creamos un centro NOC para la NOC 9
        Centros_NOC__c cNoc1 = new Centros_NOC__c();
        cNoc1.RecordTypeId = rc.Id;	        
        cNoc1.NOC__c = testIS.Id;       
        cNoc1.Descuento__c = 12;
        cNoc1.Division__c = 'Residencial';
        cNoc1.Tipo_Servicio_2__c = 'Residencial';
        cNoc1.Tipo_Estancia_2__c = 'Temporal';
        cNoc1.Tipo_Ocupacion_2__c = 'HD';
        cNoc1.Grado__c = 'Grado1';        
        insert cNoc1;
        
        testIS.Estado_Flujo__c = 'Aprobado';
        update testIS;   	
//anulo el último update debido a la nueva regla que ha añadido cristina
//
// TestTgNocAprobada.myUnitTest(), Details: System.DmlException: Update failed. First exception on row 0 with id a04b000000HNJTGAA5; 
// first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, No se puede modificar una NOC aprobada: [] Class.TestTgNocAprobada.myUnitTest: line 59, column 1        
// Eugenio
         
   		} 	
}