SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Centro</fullName>
        <active>true</active>
        <description>Residencias</description>
        <label>Centro</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/NOC__c.object
<CustomObject>
    <fields>
        <fullName>Fecha_fin__c</fullName>
        <inlineHelpText>Periodo en el que puede utilizarse la NOC</inlineHelpText>
        <label>Fecha fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Oportunidad__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Oportunidad_platform__c.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QBG6AAO</value>
            </filterItems>
            <filterItems>
                <field>Oportunidad_platform__c.Etapa__c</field>
                <operation>equals</operation>
                <value>Pendiente visita, Presentado Plan Personal, Visita Planificada / Espontánea</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Oportunidad_platform__c</referenceTo>
        <relationshipLabel>NOCs</relationshipLabel>
        <relationshipName>NOCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oportunidad_renegociada__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Oportunidad renegociada</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No se puede asignar una NOC Personal a una oportunidad cerrada. Debéis usar la NOC Renegociada</errorMessage>
            <filterItems>
                <field>Oportunidad_platform__c.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QBG6AAO</value>
            </filterItems>
            <filterItems>
                <field>Oportunidad_platform__c.Etapa__c</field>
                <operation>equals</operation>
                <value>Ingreso</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Oportunidad_platform__c</referenceTo>
        <relationshipLabel>NOCs (Oportunidad renegociada)</relationshipLabel>
        <relationshipName>NOCs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NOC</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NOCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Oportunidad_platform__c.object
<CustomObject>
    <fields>
        <fullName>Centro2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Centro</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4 OR 5 OR 6 OR 7 OR 8 OR 9)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAeAAAW</value>
            </filterItems>
            <filterItems>
                <field>Account.Activo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Director_del_centro__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Zona__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>$User.ProfileId</field>
                <operation>equals</operation>
                <value>00eb0000000dTH7AAM,00eb0000000dTHC,00eb0000000dTHH,00eb0000000zplj</value>
            </filterItems>
            <filterItems>
                <field>Account.Recepcionista__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro2__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro3__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Centro)</relationshipLabel>
        <relationshipName>Oportunidades3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOC 9 Campaña</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>NOC__c.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QBcgAAG</value>
            </filterItems>
            <filterItems>
                <field>NOC__c.Estado_Campana__c</field>
                <operation>equals</operation>
                <value>Abierta, Cerrada</value>
            </filterItems>
            <filterItems>
                <field>NOC__c.Estado_Flujo__c</field>
                <operation>equals</operation>
                <value>Aprobado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOC__c</referenceTo>
        <relationshipLabel>Oportunidades (NOC 9 Campaña)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Oportunidad</label>
    <nameField>
        <displayFormat>{YY}/{000000}</displayFormat>
        <label>Contador de Oportunidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/AvisoNocBatch.cls
global class AvisoNocBatch implements Database.Batchable<sObject>, Database.Stateful {
    global final String Query;
    private id idRTDPR;
    private id idRTDPP;

   global AvisoNocBatch(){
        idRTDPR = [Select Id From RecordType Where Name = 'NOC 11 Descuento Personal Renegociado'].Id;
        idRTDPP = '012b0000000QBcvAAG';
        Query = 'Select Id, Name, RecordTypeId, CreatedById, OwnerId, Oportunidad__c, Oportunidad__r.Centro2__r.ATC_Zona__c, Oportunidad_renegociada__c, Oportunidad_renegociada__r.Centro2__r.ATC_Zona__c From NOC__c Where (RecordTypeId = \'012b0000000QBcvAAG\' or RecordTypeId = \'' + idRTDPR + '\') and Fecha_fin__c > NEXT_N_DAYS:14 and Fecha_fin__c = NEXT_N_DAYS:15';
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(Query);
   }

    //envia mensajes a los propietarios de los recomendadores y residentes que hacen años dentro de una setmana
   global void execute(Database.BatchableContext BC, List<NOC__c> lNoc){
       //consultamos los usuarios y guardamos sus mails en un map
       Map<Id, User> users = new Map<Id, User>();
       for(User u: [Select Id, Name, Email From User]) {
           users.put(u.id, u);
       }
       
       List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
       //recorremos las noc que tenemos que informar al ATC Zona
       for(NOC__c nc : lNoc) {
           //rellenamos cada mail segun el tipo de noc y el atc zona del centro
           Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
           //guarda si existe o no el atcZona
           Boolean atcExis = false;
           if(nc.RecordTypeId == idRTDPP && nc.Oportunidad__r.Centro2__r.ATC_Zona__c != null) {
               atcExis = true;
              // mail.setToAddresses(new List<String>{users.get(nc.Oportunidad__r.Centro2__r.ATC_Zona__c).Email, 'sergi.aguilar@konozca.com'});
               mail.setToAddresses(new List<String>{users.get(nc.Oportunidad__r.Centro2__r.ATC_Zona__c).Email}); 
               mail.setSubject('Próximo vencimiento de una NOC 11 Descuento Personal Puntual'); 

           }
           else if(nc.Oportunidad_renegociada__r.Centro2__r.ATC_Zona__c != null){
               atcExis = true;
              // mail.setToAddresses(new List<String>{users.get(nc.Oportunidad_renegociada__r.Centro2__r.ATC_Zona__c).Email, 'sergi.aguilar@konozca.com'});
               mail.setToAddresses(new List<String>{users.get(nc.Oportunidad_renegociada__r.Centro2__r.ATC_Zona__c).Email});
               mail.setSubject('Próximo vencimiento de una NOC 11 Descuento Personal Renegociado'); 
           } 
           if(atcExis) {
               String body = 'Apreciado/a, \n\nLe informamos que se aproxima la fecha de vencimiento para la NOC  ( https://sarquavitae.my.salesforce.com/' + nc.Id + ' ) ' + nc.Name + ' de ' + users.get(nc.OwnerId).Name + '. \n\nReciba un cordial saludo.';
               mail.setPlainTextBody(body); 
               emails.add(mail);
           }
       }
       //enviamos los mails
       if(!Test.isRunningTest()) Messaging.sendEmail(emails);
   }

   global void finish(Database.BatchableContext BC){
   }
   
}