SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apellido_2__c</fullName>
        <inlineHelpText>Campo obligatorio para residentes. Recomendable en el resto de contactos.</inlineHelpText>
        <label>Apellido 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIF_NIF__c</fullName>
        <label>CIF/NIF</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad__c</fullName>
        <label>Ciudad</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clasificacion_tipo_Recomendador_TA__c</fullName>
        <label>Clasificación tipo Recomendador TA</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Clasificacion_tipo_recomendador__c</fullName>
        <inlineHelpText>Para la división Residencial</inlineHelpText>
        <label>Clasificación tipo Recomendador RES</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Codigo_postal__c</fullName>
        <label>Código postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Director_del_centro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio si el centro está Activo</inlineHelpText>
        <label>Director del centro</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Director Centro</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Director_centro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>División</label>
        <picklist>
            <picklistValues>
                <fullName>Residencial</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Adorea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAR Domus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domiciliaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estado_Civil__c</fullName>
        <label>Estado Civil</label>
        <picklist>
            <picklistValues>
                <fullName>Soltero/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divorciado/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viudo/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casado/a</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nuermo_Documento_Sanitario__c</fullName>
        <label>Número Documento Sanitario</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Perfil__c</fullName>
        <inlineHelpText>Campo obligatorio para residentes</inlineHelpText>
        <label>Perfil</label>
        <picklist>
            <picklistValues>
                <fullName>Autónomo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dependiente</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recepcionista__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recepcionista</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Recepcionista</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cuentas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Residencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sexo__c</fullName>
        <label>Sexo</label>
        <picklist>
            <picklistValues>
                <fullName>Hombre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mujer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Documento_Identidad__c</fullName>
        <label>Tipo Documento Identidad</label>
        <picklist>
            <picklistValues>
                <fullName>DNI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pasaporte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documento de residencia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Documento_Sanitario__c</fullName>
        <label>Tipo Documento Sanitario</label>
        <picklist>
            <picklistValues>
                <fullName>NSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MUFACE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISFAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zona_Comercial_del__c</fullName>
        <label>Zona Comercial Centro</label>
        <picklist>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Este</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mallorca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navarra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oeste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Occidental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Oriental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zaragoza</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zona_comercial__c</fullName>
        <inlineHelpText>Informar como mínimo una zona comercial si no es una sede central</inlineHelpText>
        <label>Zona Comercial RES</label>
        <picklist>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Este</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mallorca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navarra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oeste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Occidental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Oriental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zaragoza</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Centro</fullName>
        <active>true</active>
        <description>Residencias</description>
        <label>Centro</label>
    </recordTypes>
    <recordTypes>
        <fullName>Recomendador</fullName>
        <active>true</active>
        <description>Empresa donde pertenece el recomendador</description>
        <label>Entidad Recomendadora</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Oportunidad_platform__c.object
<CustomObject>
    <fields>
        <fullName>Estado_Civil__c</fullName>
        <formula>TEXT(Residente__r.Estado_Civil__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Estado Civil</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio en etapa &apos;Visita Planificada&apos;</inlineHelpText>
        <label>Residente</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAe0AAG</value>
            </filterItems>
            <filterItems>
                <field>Account.Residente__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Exitus__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Etapa__c</field>
                <operation>equals</operation>
                <value>No ingreso, Ingreso</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Residente)</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio en Etapa= &apos;Presentado Plan Personal&apos; / &apos;Negociación&apos;</inlineHelpText>
        <label>Servicio</label>
        <referenceTo>Servicio__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Oportunidad</label>
    <nameField>
        <displayFormat>{YY}/{000000}</displayFormat>
        <label>Contador de Oportunidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Servicio__c.object
<CustomObject>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Servicio__c</fullName>
        <label>Servicio</label>
        <picklist>
            <picklistValues>
                <fullName>TAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixto</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Servicio</label>
    <nameField>
        <label>Nombre de Servicio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicios</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Zona_Comercial__c</fullName>
        <label>Zona Comercial</label>
        <picklist>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Este</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mallorca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navarra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oeste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Occidental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Oriental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zaragoza</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/tareasVisitaTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class tareasVisitaTest {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        RecordType ev = [Select Id, Name From RecordType Where Name = 'Evento a Recomendador' LIMIT 1];
		RecordType cr = [Select Id, Name From RecordType Where Name = 'Contacto Recomendador' LIMIT 1];
		RecordType tr = [Select Id, Name From RecordType Where Name = 'Tarea Recomendador' LIMIT 1];
		
		Document d = new Document();
		d.Name = 'Tabla Eventos Visitas';
		d.Body = Blob.valueof('No es Director Centro ni ATC Centro del centro\n' +
		'[Zona,CentroA,CentroB,CentroC]\n' +
		'Zaragoza,6,4,2\n' +
		'Barcelona,6,4,2\n' +
		'Valencia,4,3,1\n' +
		'Centro,4,2,1\n' +
		'Sur Oriental,6,4,2\n' +
		'Sur Occidental,8,5,3\n' +
		'Mallorca,7,3,2\n' +
		'Norte,8,5,3\n' +
		'Oeste,1,1,1\n' +
		'Navarra,1,1,1\n' +
		'\n' +
		'El perfil tiene funcion de Director Centro o ATC Centro\n' +
		'[Zona,CentroA,CentroB,CentroC]\n' +
		'Zaragoza,6,4,2\n' +
		'Barcelona,3,1,1\n' +
		'Valencia,6,4,2\n' +
		'Centro,6,4,2\n' +
		'Sur Oriental,3,1,1\n' +
		'Sur Occidental,3,2,1\n' +
		'Mallorca,4,2,1\n' +
		'Norte,6,4,2\n' +
		'Oeste,5,2,1\n' +
		'Navarra,1,1,1\n');	
		d.FolderId = UserInfo.getUserId();
		insert d;
		
		User uAux = [Select Id, Zona_Comercial__c, ProfileId From User WHERE IsActive = true LIMIT 1];    
        User uAux2 = [Select Id, Zona_Comercial__c, ProfileId From User WHERE IsActive = true and profile.name = 'Comercial TA' LIMIT 1]; 
		
		Account rec = new Account();
		rec.RecordTypeId = cr.Id;
        rec.personEmail = 'test@test.com';
		rec.LastName = 'rec1';
		rec.Phone = '444484948844';
		rec.Clasificacion_tipo_recomendador__c = 'A';
        rec.Clasificacion_tipo_Recomendador_TA__c = 'A';
         rec.Residencial__c = true;
		triggerHelper.recursiveHelper1(true);
		insert rec;
		triggerHelper.recursiveHelper1(false);
		
		Contact rec2 = new Contact();
		rec2.LastName = 'rec2';
		rec2.Phone = '123456789';
		//rec2.AccountId = rec.Id;
		insert rec2;

		Event e = new Event();
		e.RecordTypeId = ev.Id;
		e.OwnerId = uAux.Id;
		e.Subject= 'Visita';
		e.WhoId = rec2.Id;
		e.Resultado__c = 'Acción Cerrada';
		e.StartDateTime = System.now();
		e.EndDateTime = System.now();
		insert e;
        
        Event et = new Event();
		et.RecordTypeId = ev.Id;
		et.OwnerId = uAux2.Id;
		et.Subject= 'Visita';
		et.WhoId = rec2.Id;
		et.Resultado__c = 'Acción Cerrada';
		et.StartDateTime = System.now();
		et.EndDateTime = System.now();
		insert et;
		
		
		Servicio__c sc = new Servicio__c();
        sc.Name = 'serv';
        insert sc;
        
		Account a1 = new Account();
        a1.FirstName = '1';
        a1.LastName = 'cliente1 apell';
        a1.Apellido_2__c = 'apell';
        a1.Perfil__c = 'Autónomo';
        a1.personemail = 'test@test.com';
        a1.Idioma_de_Contacto__pc = 'Catalan';
        a1.Residente__c = true;
        a1.Phone = '523423423455';
        a1.RecordTypeId = '012b0000000QAe0AAG';
        a1.CIF_NIF__c = '32146871R';
        a1.Tipo_Documento_Sanitario__c = 'NCS';
        a1.Nuermo_Documento_Sanitario__c = '111';
        a1.Estado_Civil__c = 'Casado/a';
        a1.Sexo__c = 'Hombre';
        a1.Tipo_Documento_Identidad__c = 'DNI';
        a1.CIF_NIF__c = '47794178V';
        a1.Calle__c = 'Carrer de buenos aires 34';
        a1.Ciudad__c = 'Barcelona';
        a1.PersonBirthdate = Date.today();
        a1.Codigo_postal__c  = '08036';
        triggerHelper.recursiveHelper1(true);
        insert a1;
        triggerHelper.recursiveHelper1(false);
        
		Account centro1 = new Account();
        centro1.Name = 'Centro1';
        centro1.RecordTypeId = '012b0000000QAeAAAW';
        centro1.Zona_Comercial_del__c = 'Centro';
        centro1.Phone = '442342343244';
        centro1.Activo__c = true;
        centro1.Director_del_centro__c = '005b0000001JTCKAA4';
        centro1.Recepcionista__c = '005b0000001JSQ6';
        centro1.Division__c = 'Residencial';
        triggerHelper.recursiveHelper1(true);
        insert centro1;
        triggerHelper.recursiveHelper1(false);
        
        Oportunidad_platform__c op = new Oportunidad_platform__c();
        op.Residente__c = a1.Id;
        op.Etapa__c = 'Pendiente visita';
        op.Centro2__c = centro1.Id;
        op.Canal__c = 'Llamada al Cat';
        op.Procedencia__c = 'Vecindad';
        op.Tipo_de_pago__c = 'gratis';
        op.Regimen__c = 'UED';
        op.RecordTypeId = '012b0000000QBG6AAO';
        op.Tipo_de_Financiacion__c = 'Privado';
        op.Fecha_prevista_de_ingreso__c = Date.today();
        op.Motivio_de_Alta_GCR__c = 'si';
        op.No_se_solicita_descuento__c=true;
        triggerHelper.recursiveHelper1(true);
        insert op;
        triggerHelper.recursiveHelper1(false);
        
        Event e2 = new Event();
		e2.RecordTypeId = '012b0000000QBdeAAG';
		e2.Subject= 'Visita concertada';
		e2.WhoId = rec2.Id;
		e2.WhatId = op.Id;
		e2.StartDateTime = System.now().addDays(5);
		e2.EndDateTime = System.now().addDays(5);
		e2.Lugar_de_la_visita__c = 'centro';
        e2.OwnerId = uAux2.Id;
		insert e2;
		
    }
}