SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Apellido_2__c</fullName>
        <inlineHelpText>Campo obligatorio para residentes. Recomendable en el resto de contactos.</inlineHelpText>
        <label>Apellido 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIF_NIF__c</fullName>
        <label>CIF/NIF</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad__c</fullName>
        <label>Ciudad</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Codigo_postal__c</fullName>
        <label>Código postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>División</label>
        <picklist>
            <picklistValues>
                <fullName>Residencial</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Adorea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAR Domus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domiciliaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estado_Civil__c</fullName>
        <label>Estado Civil</label>
        <picklist>
            <picklistValues>
                <fullName>Soltero/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divorciado/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viudo/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casado/a</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fuente__c</fullName>
        <label>Fuente</label>
        <picklist>
            <picklistValues>
                <fullName>Colectivos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consejeros SARquavitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contactos Corporativos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jornadas y eventos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prensa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profesionales SARquavitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suscriptores blog</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suscriptores Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web (formularios)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webs sector</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>No_tiene_telefono__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No tiene teléfono</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nuermo_Documento_Sanitario__c</fullName>
        <label>Número Documento Sanitario</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Perfil__c</fullName>
        <inlineHelpText>Campo obligatorio para residentes</inlineHelpText>
        <label>Perfil</label>
        <picklist>
            <picklistValues>
                <fullName>Autónomo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dependiente</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sexo__c</fullName>
        <label>Sexo</label>
        <picklist>
            <picklistValues>
                <fullName>Hombre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mujer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Documento_Identidad__c</fullName>
        <label>Tipo Documento Identidad</label>
        <picklist>
            <picklistValues>
                <fullName>DNI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pasaporte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documento de residencia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Documento_Sanitario__c</fullName>
        <label>Tipo Documento Sanitario</label>
        <picklist>
            <picklistValues>
                <fullName>NSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MUFACE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISFAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VIP</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Categoria_Profesional__c</fullName>
        <label>Categoría Profesional</label>
        <picklist>
            <picklistValues>
                <fullName>Directivo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enfermero</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jefes de Servicio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mandos Intermedios</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Médico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profesionales -por cuenta ajena-</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Propietario Negocio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Técnico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trabajador Social</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ciudad__c</fullName>
        <label>Ciudad</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Codigo_Postal__c</fullName>
        <label>Código Postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departamento__c</fullName>
        <label>Departamento</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>División</label>
        <picklist>
            <picklistValues>
                <fullName>Adorea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residencial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domiciliaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SARDomus</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Especialidad_Medica__c</fullName>
        <label>Especialidad Médica</label>
        <picklist>
            <picklistValues>
                <fullName>Cardiólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cirujano</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermatólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diagnostico por Imagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endocrino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enfermero (DUE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gastroenterólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gerontólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ginecólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hematólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infectólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicina de Familia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicina Interna</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicina Preventiva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Médico de Família</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Microbiólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nefrólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neumólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neurólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nutricionista</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oftalmólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paliatólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pediatra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psicólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Traumatólogo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UCI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urgencias</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urólogo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fuente__c</fullName>
        <label>Fuente</label>
        <picklist>
            <picklistValues>
                <fullName>Consejeros SARquavitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consejeros Confide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancs y Cajas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dirección General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presidencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contactos corporativos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profesionales SARquavitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profesionales Confide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prensa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webs sector</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jornadas y eventos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suscritores blogs centros</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Idioma_de_contacto__c</fullName>
        <label>Idioma de contacto</label>
        <picklist>
            <picklistValues>
                <fullName>Castellano</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Catalán</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Euskera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gallego</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inglés</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>No_tiene_telefono__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No tiene teléfono</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sexo__c</fullName>
        <label>Sexo</label>
        <picklist>
            <picklistValues>
                <fullName>Hombre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mujer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VIP</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/TestTrigger_Candidats_To_account.cls
/** 
* File Name:   TestTrigger_Candidats_To_account
* Description: Test del trigger TriggerCandidatsToAccount
* Copyright:   Konozca 
* @author:     Alexander Gimenez
* Modification Log 
* =============================================================== 
*Date          Author           Modification 
 15/12/2014     AGimenez 
* =============================================================== 
**/

// El caso que se prueba es creando dos Cuentas con el mismo correo, una vip y otra no
// Creamosa continuacion una Lead con el mismo correo y que llene algunos de los campos 
// que la de vip no tenia, asi como algunos campos que si que tenian ambas. 
// El test comprueba que los cambios se han realizado efectivamente. 


@istest
private class TestTrigger_Candidats_To_account {
    static testMethod void myUnitTest() {
       // Creamos un account de tipo  no vip y tipo Servicios centrales
       Account a1 = new Account();
        a1.FirstName = 'Servicios';
        a1.PersonEmail = 'testtest@test.com';
        a1.LastName = 'centrales';
        a1.Perfil__c = 'Autónomo';
        a1.Idioma_de_Contacto__pc = 'Catalan';
        a1.Residente__c = true;
        a1.Phone = '523423423455';
        a1.Fuente__c= 'Consejeros Confide;Bancos y Cajas';
        a1.RecordTypeId = '012b0000000QFtb';
        a1.CIF_NIF__c = '53652208A';
        a1.Tipo_Documento_Sanitario__c = 'NCS';
        a1.Nuermo_Documento_Sanitario__c = '111';
        a1.Estado_Civil__c = 'Casado/a';
        a1.Sexo__c = 'Hombre';
        a1.Tipo_Documento_Identidad__c = 'DNI';
        a1.CIF_NIF__c = '04304479Y';
        a1.Calle__c = 'Carrer de buenos aires 34';
        a1.Ciudad__c = 'Barcelona';
        a1.VIP__c = false;
        a1.PersonBirthdate = Date.today().addDays(-15);
        a1.Codigo_postal__c  = '08036';
        triggerHelper.recursiveHelper1(true);
        insert a1;
        triggerHelper.recursiveHelper1(false);

		// Creo una cuenta tipo vip y servicios centrales 
		Account a2 = new Account();
        a2.FirstName = '2';
        a2.LastName = 'cliente2 apell';
        a2.PersonEmail ='test@test.com';
        a2.Perfil__c = 'Autónomo';
        a2.Apellido_2__c = 'apell';
        a2.Residente__c = true;
        a2.Categoria_Profesional__pc = 'Enfermero';
        a2.Especialidad_Medica__pc = '';
        a2.RecordTypeId = '012b0000000QFtb';
        a2.Tipo_Documento_Sanitario__c = 'NCS';
        a2.Tipo_Documento_Identidad__c = 'DNI';
        a2.CIF_NIF__c =  '71501448Z';
        a2.Nuermo_Documento_Sanitario__c = '222';
        a2.PersonEmail = 'testtest@test.com';
        a2.Sexo__c = 'Hombre';
        a2.Phone = '5552342343245';
        a2.Calle__c = 'Gran Via 24';
        a2.Ciudad__c = 'Madrid';
        a2.Vip__c = true;
        a2.PersonBirthdate = Date.today();
        a2.Codigo_postal__c  = '28013';
        triggerHelper.recursiveHelper1(true);
        insert a2;
        triggerHelper.recursiveHelper1(false);      
        
   		 // Creamos una Lead de tipo vip 
		Lead l1 = new Lead();
		l1.FirstName = 'Servicios';
        l1.LastName = 'centrales';
        l1.Idioma_de_contacto__c = 'Catalan';
       	l1.Sexo__c = 'Hombre';
        l1.VIP__c = false;
        l1.Fuente__c= 'Web';
        l1.Division__c = 'TESTING';
        // PROVAMOS EL CASO QUE HACE SALTAR LA REGLA DE VALIDACION PARA VER SI EL TRIGGER ESTA BIEN PROGRAMADO
        l1.Categoria_Profesional__c = 'Enfermero';
        l1.Especialidad_Medica__c = 'Gastroenterólogo';
        l1.Departamento__c = 'Ventas';
        l1.Email = 'testtest@test.com';
        l1.No_tiene_telefono__c = false;
        l1.Ciudad__c = 'Barcelona';
        l1.Provincia__c = 'Barcelona';
        l1.Fax='8888888';
        l1.Codigo_Postal__c = '08110';
        l1.Calle__c = 'Julio Garcia 16B';
        l1.Country = 'España';
        l1.MobilePhone = '606975863';
        triggerHelper.recursiveHelper1(true);
        insert l1;
        triggerHelper.recursiveHelper1(false);
        
        // Creamos una Lead de tipo vip 
		Lead l2 = new Lead();
		l2.FirstName = 'VIP';
        l2.LastName = 'VIP';
        l2.Idioma_de_contacto__c = 'Catalan';
       	l2.Sexo__c = 'Hombre';
        l2.VIP__c = true;
        l2.Fuente__c= 'Web';
        l2.Division__c = 'TESTING';
        l2.Categoria_Profesional__c = 'Directivo';
        l2.Especialidad_Medica__c = 'Gastroenterólogo';
        l2.Departamento__c = 'Ventas';
        l2.Email = 'testtest@test.com';
        l2.No_tiene_telefono__c = false;
        l2.Ciudad__c = 'Barcelona';
        l2.Provincia__c = 'Barcelona';
        l2.Codigo_Postal__c = '08110';
        l2.Calle__c = 'Julio Garcia 16B';
        l2.Country = 'España';
        l2.MobilePhone = '606975863';
        triggerHelper.recursiveHelper1(true);
        insert l2;
        triggerHelper.recursiveHelper1(false);   
     }    
}