SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Correo_Electronico_Generico__c</fullName>
        <label>Correo Electrónico Genérico</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>NIF_director_centro__c</fullName>
        <label>NIF director centro</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nombre_Tablet_1__c</fullName>
        <label>Nombre Tablet 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Nombre_Tablet_2__c</fullName>
        <label>Nombre Tablet 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Nombre_Tablet_3__c</fullName>
        <label>Nombre Tablet 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tableta_1__c</fullName>
        <description>Identificador del número de la tableta</description>
        <inlineHelpText>Identificador del número de la tableta</inlineHelpText>
        <label>ID Tableta 1</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tableta_2__c</fullName>
        <description>Identificador del número de la tableta</description>
        <inlineHelpText>Identificador del número de la tableta</inlineHelpText>
        <label>ID Tableta 2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tableta_3__c</fullName>
        <description>Identificador del número de la tableta</description>
        <inlineHelpText>Identificador del número de la tableta</inlineHelpText>
        <label>ID Tableta 3</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utiliza_firma_biometrica__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Utilización la firma biométrica para la generación del contrato.</description>
        <inlineHelpText>Utilizar la firma biométrica para generar el contrato?</inlineHelpText>
        <label>Utiliza firma biométrica</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>passVidsigner__c</fullName>
        <description>Contraseña de suscripción del centro a VidSigner</description>
        <label>passVidsigner</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userVidsigner__c</fullName>
        <description>User de la suscripción a VidSigner</description>
        <label>userVidsigner</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Oportunidad_platform__c.object
<CustomObject>
    <fields>
        <fullName>Apellido_Avalista__c</fullName>
        <label>Apellido Avalista</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apellido_representante_legal__c</fullName>
        <label>Apellido representante legal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Autorizacion_judicial_de_internamiento__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mediante auto de autorización judical de internamiento</inlineHelpText>
        <label>Autorización judicial de internamiento</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Centro2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Centro</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4 OR 5 OR 6 OR 7 OR 8 OR 9)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAeAAAW</value>
            </filterItems>
            <filterItems>
                <field>Account.Activo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Director_del_centro__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Zona__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>$User.ProfileId</field>
                <operation>equals</operation>
                <value>00eb0000000dTH7AAM,00eb0000000dTHC,00eb0000000dTHH,00eb0000000zplj</value>
            </filterItems>
            <filterItems>
                <field>Account.Recepcionista__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro2__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro3__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Centro)</relationshipLabel>
        <relationshipName>Oportunidades3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DNI_Avalista__c</fullName>
        <label>DNI Avalista</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNI_Director__c</fullName>
        <formula>Centro2__r.NIF_director_centro__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DNI Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNI_Pagador__c</fullName>
        <formula>Pagador__r.CIF_NIF__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DNI Pagador</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNI_Residente__c</fullName>
        <formula>Residente__r.CIF_NIF__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DNI Residente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNI_representante_legal__c</fullName>
        <label>DNI representante legal</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Director_Centro_First__c</fullName>
        <formula>Centro2__r.Director_del_centro__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Director Centro First</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Director_Centro_Last__c</fullName>
        <formula>Centro2__r.Director_del_centro__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Director Centro Last</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enviado_a_signar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si el PDF del contrato a sido enviado a ViDSigner</description>
        <label>Enviado a signar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ID_Doc_Firmado__c</fullName>
        <description>Identificador del documento enviado para firmar al webservice ViDSigner</description>
        <label>ID Doc Firmado</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nombre_Avalista__c</fullName>
        <label>Nombre Avalista</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nombre_propio_y_plena_capacidad_de__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>En nombre propio y con plena capacidad de obrar y obligarse</inlineHelpText>
        <label>Nombre propio y plena capacidad</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nombre_representante_legal__c</fullName>
        <label>Nombre representante legal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pagador_First_Name__c</fullName>
        <formula>Pagador__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pagador First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pagador_Last_Name__c</fullName>
        <formula>Pagador__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pagador Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pagador__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pagador</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAe0AAG</value>
            </filterItems>
            <filterItems>
                <field>Account.Exitus__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Pagador)</relationshipLabel>
        <relationshipName>OportunidadesPagador</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Persona_de_referencia__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>A través de la persona de referencia</inlineHelpText>
        <label>Persona de referencia</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Representate_legagal__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>A través de su representante legal</inlineHelpText>
        <label>Representate legal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Residente_First_Name__c</fullName>
        <formula>Residente__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Residente First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residente_Last_Name__c</fullName>
        <formula>Residente__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Residente Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio en etapa &apos;Visita Planificada&apos;</inlineHelpText>
        <label>Residente</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAe0AAG</value>
            </filterItems>
            <filterItems>
                <field>Account.Residente__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Exitus__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Etapa__c</field>
                <operation>equals</operation>
                <value>No ingreso, Ingreso</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Residente)</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Oportunidad</label>
    <nameField>
        <displayFormat>{YY}/{000000}</displayFormat>
        <label>Contador de Oportunidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/escogerTableta.cls
public with sharing class escogerTableta {

    String tableta= null;
    
    public Oportunidad_platform__c op {get;set;}
    public Account ac {get;set;}
    public class xException extends Exception {}
    public String idTablet {
        get;
        // *** setter is NOT being called ***
        set {
            idTablet = value;
        }
    } 
    public String pagOP {
        get;
        // *** setter is NOT being called ***
        set {
            pagOP = value;
        }
    }      
    private Map<String, String> result;
    List<SelectOption> options;

    public escogerTableta(){
        op = [ SELECT id, Name, RecordType.Name, Centro2__c, 
              Director_Centro_First__c, Director_Centro_Last__c, DNI_Director__c,
              Residente_First_Name__c, Residente_Last_Name__c, DNI_Residente__c, Autorizacion_judicial_de_internamiento__c,
              Nombre_representante_legal__c, Apellido_representante_legal__c, DNI_representante_legal__c,
              Nombre_propio_y_plena_capacidad_de__c, Representate_legagal__c, Persona_de_referencia__c, 
              Nombre_Avalista__c, Apellido_Avalista__c, DNI_Avalista__c,
              Pagador_First_Name__c, Pagador_Last_Name__c, Residente__c, DNI_Pagador__c,
              ID_Doc_Firmado__c, Enviado_a_signar__c, Pagador__c
              FROM Oportunidad_platform__c 
              WHERE id =: ApexPages.currentPage().getParameters().get('id') ];
        ac = [ SELECT id, Name, Correo_Electronico_Generico__c, Utiliza_firma_biometrica__c, NIF_director_centro__c, Tableta_1__c, Tableta_2__c, Tableta_3__c, 
                Nombre_Tablet_1__c, Nombre_Tablet_2__c, Nombre_Tablet_3__c, userVidsigner__c, passVidsigner__c  
               FROM Account WHERE id =: op.Centro2__c ];

        
    }
  
    public PageReference enviarPDF() {
       
        REST_WebService ws = new REST_WebService(ac.userVidsigner__c, ac.passVidsigner__c);
        if(op.Enviado_a_signar__c){
            result = new Map<String, String>();
            result.put(REST_WebService.STATUS, 'El contrato ya se ha enviado a signar');
            return null;
        }
        Map<String, Object> p = new Map<String, Object>();
        p.put(REST_WebService.USER_VIDSIGNER, ac.userVidsigner__c);
        p.put(REST_WebService.PASS_VIDSIGNER, ac.passVidsigner__c);        
        p.put(REST_WebService.OP_ID , String.valueOf(op.id));
        p.put(REST_WebService.OP_NAME, op.Name);
        p.put(REST_WebService.EMAIL, (ac.Correo_Electronico_Generico__c!=null) ? ac.Correo_Electronico_Generico__c : '');
        p.put(REST_WebService.TABLET_ID, idTablet);
        p.put(REST_WebService.SIGNERS , CalloutVidsigner.getSigners(ac, op));
        
        result = ws.postDocuments(p);
        
        if(result !=null && result.get(REST_WebService.STATUS)=='OK'){ //PDF subido correctamente -> guardar ID Doc
            String docGUI = CalloutVidsigner.getJSONValue(result.get(REST_WebService.RESPONSE), 'DocGUI');
            op.ID_Doc_Firmado__c = docGUI;
            op.Enviado_a_signar__c = true;
            update op;
        }
        
        return null;
    }

    public List<SelectOption> getItems() {
        options = new List<SelectOption>();
        
        if(ac.Tableta_1__c!=null && ac.Tableta_1__c !=''){
            options.add(new SelectOption(ac.Tableta_1__c, ac.Nombre_Tablet_1__c ));     
        }
        if(ac.Tableta_2__c!=null && ac.Tableta_2__c !=''){
            options.add(new SelectOption(ac.Tableta_2__c, ac.Nombre_Tablet_2__c ));      
        }
        if(ac.Tableta_3__c!=null && ac.Tableta_3__c !=''){
            options.add(new SelectOption(ac.Tableta_3__c, ac.Nombre_Tablet_3__c ));     
        }
        
        return options;
    }
    
    public String getTableta() {
        return tableta;
    }
    
    public void setTableta(String tableta) { 
        this.tableta = tableta; 
    }
  
    public String getResult(){
        String r = 'a';
         r = (result!=null) ? result.get(REST_WebService.RESPONSE) : '';
            if(r.contains('DocGUI')){
                r = result.get(REST_WebService.STATUS);
            }

            return r;
        //return (result!=null) ? result.get(REST_WebService.RESPONSE) : '';
        //return ( (r!=null) ? (r.contains('DocGUI') ? result.get(REST_WebService.STATUS) : r );
    }
 
    public String getVisible(){
        return (result==null) ? 'display:none;' : '';
    }
   
    public PageReference backOP(){
        return new PageReference('/' + op.Id);
    }    

}