SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Residente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residente</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Centro</fullName>
        <active>true</active>
        <description>Residencias</description>
        <label>Centro</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/NOC__c.object
<CustomObject>
    <fields>
        <fullName>Centro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>En caso que aplique a un centro en concreto</inlineHelpText>
        <label>Centro</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAeAAAW</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NOCs</relationshipLabel>
        <relationshipName>NOCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Descuento__c</fullName>
        <formula>1-(Precio_propuesto__c  /   Precio_actual__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Descuento</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Informar si el convenio aplica para un sólo tipo de servicio</inlineHelpText>
        <label>Servicio</label>
        <referenceTo>Servicio__c</referenceTo>
        <relationshipLabel>NOCs</relationshipLabel>
        <relationshipName>NOCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NOC</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NOCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Oportunidad_platform__c.object
<CustomObject>
    <fields>
        <fullName>Centro2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Centro</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4 OR 5 OR 6 OR 7 OR 8 OR 9)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAeAAAW</value>
            </filterItems>
            <filterItems>
                <field>Account.Activo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Director_del_centro__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Zona__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>$User.ProfileId</field>
                <operation>equals</operation>
                <value>00eb0000000dTH7AAM,00eb0000000dTHC,00eb0000000dTHH,00eb0000000zplj</value>
            </filterItems>
            <filterItems>
                <field>Account.Recepcionista__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro2__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro3__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Centro)</relationshipLabel>
        <relationshipName>Oportunidades3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Centro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio si Procedencia=Centro Sarquavitae</inlineHelpText>
        <label>Centro de procedencia</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAeAAAW</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Centro de procedencia)</relationshipLabel>
        <relationshipName>Oportunidades2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Descuento_Ofertado__c</fullName>
        <label>Descuento Ofertado</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Descuento__c</fullName>
        <label>Descuento NOC</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Fecha_de_Alta__c</fullName>
        <label>Fecha de Alta</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fecha_finalizacion__c</fullName>
        <inlineHelpText>Residencial: Campo obligatorio si el tipo de estancia es &apos;Temporal&apos;</inlineHelpText>
        <label>Fecha finalización</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NOC_11_Centro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOC 11 Centro</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>NOC__c.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QBcqAAG</value>
            </filterItems>
            <filterItems>
                <field>NOC__c.Estado_Flujo__c</field>
                <operation>equals</operation>
                <value>Aprobado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOC__c</referenceTo>
        <relationshipLabel>Oportunidades (NOC 11 Centro)</relationshipLabel>
        <relationshipName>Oportunidades3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOC 9 Campaña</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>NOC__c.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QBcgAAG</value>
            </filterItems>
            <filterItems>
                <field>NOC__c.Estado_Campana__c</field>
                <operation>equals</operation>
                <value>Abierta, Cerrada</value>
            </filterItems>
            <filterItems>
                <field>NOC__c.Estado_Flujo__c</field>
                <operation>equals</operation>
                <value>Aprobado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOC__c</referenceTo>
        <relationshipLabel>Oportunidades (NOC 9 Campaña)</relationshipLabel>
        <relationshipName>Oportunidades1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_Finanza__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Fianza</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Precio_Plus__c</fullName>
        <label>Precio Plus</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Precio_Total__c</fullName>
        <formula>if( ISBLANK( Precio_Plus__c ), 
IF( Precio_Ofertado__c &lt;&gt;0 , 
Precio_Ofertado__c, IF(Descuento_Ofertado__c&lt;&gt;0, Precio__c *(1- Descuento_Ofertado__c ),Precio__c *(1- Descuento__c )) 
), 

IF( Precio_Ofertado__c &lt;&gt;0 , 
Precio_Ofertado__c, IF(Descuento_Ofertado__c&lt;&gt;0, (Precio__c *(1- Descuento_Ofertado__c ))+Precio_Plus__c,((Precio__c+Precio_Plus__c) *(1- Descuento__c ))) 
) 
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Precio Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio en etapa &apos;Visita Planificada&apos;</inlineHelpText>
        <label>Residente</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAe0AAG</value>
            </filterItems>
            <filterItems>
                <field>Account.Residente__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Exitus__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Etapa__c</field>
                <operation>equals</operation>
                <value>No ingreso, Ingreso</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Residente)</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio en Etapa= &apos;Presentado Plan Personal&apos; / &apos;Negociación&apos;</inlineHelpText>
        <label>Servicio</label>
        <referenceTo>Servicio__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tarifa__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Tarifa</label>
        <referenceTo>Tarifa__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Oportunidad</label>
    <nameField>
        <displayFormat>{YY}/{000000}</displayFormat>
        <label>Contador de Oportunidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Servicio__c.object
<CustomObject>
    <fields>
        <fullName>Servicio__c</fullName>
        <label>Servicio</label>
        <picklist>
            <picklistValues>
                <fullName>TAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixto</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Servicio</label>
    <nameField>
        <label>Nombre de Servicio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicios</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Tarifa__c.object
<CustomObject>
    <fields>
        <fullName>Centro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Centro</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAeAAAW</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tarifas</relationshipLabel>
        <relationshipName>Tarifas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOC</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>NOC__c.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QBclAAG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOC__c</referenceTo>
        <relationshipLabel>Tarifas</relationshipLabel>
        <relationshipName>Tarifas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Precio_Plus__c</fullName>
        <label>Precio Plus</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Servicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Servicio</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Servicio__c.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QIES</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Servicio__c</referenceTo>
        <relationshipLabel>Tarifas</relationshipLabel>
        <relationshipName>Tarifas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tarifa</label>
    <nameField>
        <label>Nombre de Tarifa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tarifas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/GenerateOpportunity.cls
public with sharing class GenerateOpportunity {

    public Oportunidad_platform__c ofc{get; set;}
    public Account res{get; set;}
    public Account centro{get; set;}
    public Tarifa__c tarifa{get; set;}
    public Servicio__c serv{get; set;}
    public NOC__c noc{get; set;}
    public String nocGet{get; set;}
    public String ATCName{get; set;}
    public String td{get; set;}
    public String fianza{get; set;}
    public String temps{get; set;}
    public String fFi{get; set;}
    public String tarifaOfic{get; set;}
    public String fila1{get; set;}
    public String fila2{get; set;}
    public String fila3{get; set;}
    public String fila4{get; set;}
    public String tit1{get; set;}
    public String tit2{get; set;}
    public String tit3{get; set;}
    public String tit4{get; set;}
    public Double descnto{get; set;}
    public List<String> mes = new List<String> {'', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'};
    
    public GenerateOpportunity(ApexPages.StandardController controller) {
        ofc = [SELECT Id, Name, CreatedBy.Name, Fecha_de_Alta__c, Residente__c, Centro2__c, Tarifa__c, No_Finanza__c, Precio_Total__c, Descuento__c, Descuento_Ofertado__c, Servicio__c, Precio_Plus__c, Fecha_finalizacion__c, NOC__c, NOC_11_Centro__c, NOC_11_Persona__c, NOC_12_Convenios__c FROM Oportunidad_platform__c WHERE Id = :controller.getId()];
        res = [SELECT Id, Name, CIF_NIF__c, Idioma_de_Contacto__pc FROM Account WHERE Id = :ofc.Residente__c];
        centro = [SELECT Id, Name, Ciudad__c, ATC_Centro2__c, Director_del_centro__c FROM Account WHERE Id = :ofc.Centro2__c];
        
        tarifa = [Select Id, Servicio__c, Centro__c, NOC__c, Tipo_Tarifa__c, Precio__c, Precio_Plus__c From Tarifa__c Where Id = :ofc.Tarifa__c];
        
        serv = [SELECT Id, Tipo_Ocupacion__c, Grado_Dependencia__c FROM Servicio__c WHERE Id = :ofc.Servicio__c];
        if(tarifa.Tipo_Tarifa__c == 'Diaria') {
             fianza = '0.00';
             temps = 'diaria';
        }
        else {
            fianza = ofc.Precio_Total__c +'';
            temps = 'mensual';
        }
        Id nc = Null;
        if(ofc.NOC__c != NULL) nc = ofc.NOC__c;
        else if (ofc.NOC_11_Centro__c != NULL) nc = ofc.NOC_11_Centro__c;
        else if (ofc.NOC_11_Persona__c != NULL) nc = ofc.NOC_11_Persona__c;
        else if(ofc.NOC_12_Convenios__c != NULL) nc = ofc.NOC_12_Convenios__c;
        else {
            nocGet = ' ';
        }
        if(nc != NULL){
            noc = [SELECT Id, Name FROM NOC__c WHERE Id = :nc];
            nocGet = '('+noc.Name+')';
        }
        
        td = '' + Date.today().day() + ' de ' + mes[Date.today().month()] + ' de ' + Date.today().year();
        fFi = Date.today().addDays(30).day() + '-' + Date.today().addDays(30).month() + '-' + Date.today().addDays(30).year();
        if(ofc.Precio_Plus__c != NULL) tarifaOfic = String.ValueOf(ofc.Precio_Plus__c + tarifa.Precio__c);
        else tarifaOfic = String.ValueOf(tarifa.Precio__c);
        User atc = new User();
        if(centro.ATC_Centro2__c != null) atc = [Select Id, Name From User WHERE Id = :centro.ATC_Centro2__c];
        else if (centro.Director_del_centro__c != null) atc = [Select Id, Name From User WHERE Id = :centro.Director_del_centro__c];
        if(atc != null) ATCName = '     ' + atc.Name; 
        else ATCName = ' ';
        if(tarifaOfic.endsWith('.0')) tarifaOfic.replace('.0', '.00');
        fila1 = fila2 = fila3 = fila4 = '';
        tit1 = tit2 = tit3 = tit4 = '';
        //escribimos en las filas
        String serTOc = '';
        if(serv.Tipo_Ocupacion__c == 'HI') serTOc = 'Habitación Individual';
        else if(serv.Tipo_Ocupacion__c == 'HD') serTOc = 'Habitación Doble';
        else serTOc = serv.Tipo_Ocupacion__c;
        
        fila1 = temps + ' ' + serTOc;
        tit1  = '• Servicio: ';
        if(ofc.Descuento__c == null || ofc.Descuento_Ofertado__c <= 0) {
            tit2 = '• Precio Final: ';
            fila2 = ofc.Precio_Total__c + '€';
        }
        else {
            tit3 = '• Promoción: ';
            tit4 = '• Precio Final: ';
            fila2 = '• Tarifa oficial: ' + tarifaOfic + '€';
            
            if (ofc.Descuento_Ofertado__c!= NULL) fila3 = ofc.Descuento_Ofertado__c + '% ';
            else if(ofc.Descuento__c!= NULL) fila3 = ofc.Descuento__c + '% ';
            
            fila4 = ofc.Precio_Total__c + '€';
        }
        
    }
}