SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CIF_NIF__c</fullName>
        <label>CIF/NIF</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad__c</fullName>
        <label>Ciudad</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clasificacion_tipo_recomendador__c</fullName>
        <inlineHelpText>Para la división Residencial</inlineHelpText>
        <label>Clasificación tipo Recomendador RES</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Codigo_postal__c</fullName>
        <label>Código postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estado_Civil__c</fullName>
        <label>Estado Civil</label>
        <picklist>
            <picklistValues>
                <fullName>Soltero/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divorciado/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viudo/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casado/a</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Historia_de_vida_adjunta__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Historia de vida adjunta</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IdNAV_RES__c</fullName>
        <label>IdNAV_RES</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nuermo_Documento_Sanitario__c</fullName>
        <label>Número Documento Sanitario</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pais__c</fullName>
        <label>País</label>
        <picklist>
            <picklistValues>
                <fullName>España</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>U.E.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No U.E.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Perfil__c</fullName>
        <inlineHelpText>Campo obligatorio para residentes</inlineHelpText>
        <label>Perfil</label>
        <picklist>
            <picklistValues>
                <fullName>Autónomo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dependiente</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferencia_de_envio_de_factura__c</fullName>
        <label>Preferencia de envío de factura</label>
        <picklist>
            <picklistValues>
                <fullName>Recogida en centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correo ordinario</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provincia__c</fullName>
        <label>Provincia</label>
        <picklist>
            <picklistValues>
                <fullName>A Coruña</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alacant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Álava</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albacete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Almería</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asturias</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ávila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Badajoz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bizkaia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burgos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cáceres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cádiz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cantabria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Castelló</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceuta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ciudad Real</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Córdoba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuenca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gipuzkoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Girona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guadalajara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huelva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huesca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illes Balears</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaén</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>La Rioja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Las Palmas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>León</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Residencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sexo__c</fullName>
        <label>Sexo</label>
        <picklist>
            <picklistValues>
                <fullName>Hombre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mujer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Documento_Identidad__c</fullName>
        <label>Tipo Documento Identidad</label>
        <picklist>
            <picklistValues>
                <fullName>DNI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pasaporte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documento de residencia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Documento_Sanitario__c</fullName>
        <label>Tipo Documento Sanitario</label>
        <picklist>
            <picklistValues>
                <fullName>NSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MUFACE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISFAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Centro</fullName>
        <active>true</active>
        <description>Residencias</description>
        <label>Centro</label>
    </recordTypes>
    <recordTypes>
        <fullName>Recomendador</fullName>
        <active>true</active>
        <description>Empresa donde pertenece el recomendador</description>
        <label>Entidad Recomendadora</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Res_Aux__c.object
<CustomObject>
    <label>Res Aux</label>
    <nameField>
        <label>Nombre de Res Aux</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Res Aux</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/TestBatchAsignarVista.cls
/** 
* File Name:   TestBatchAsignarVista 
* Description: Test para el BatchAsignarVisita 
* Copyright:   Konozca 
* @author:     Jose M Perez
* Modification Log 
* Fecha: 10/02/2016 
* =============================================================== 
**/

@isTest
private class TestBatchAsignarVista {
    static testMethod void myUnitTest() {
        Date avui = date.today();
        Integer mesActual = avui.month();
        //Crear Residente
        Account residente1 = new Account();
        residente1.RecordTypeId = getRecordTypeId('Contacto Recomendador');
        residente1.Clasificacion_tipo_recomendador__c = 'A';
        residente1.Residencial__c = true;
        residente1.FirstName = 'Nombre1';
        residente1.LastName = 'Apellido1';
        residente1.Residente__c = true;
        residente1.Perfil__c = 'Autónomo';
        residente1.Sexo__c = 'Hombre';
        residente1.Estado_Civil__c = 'Soltero/a';
        residente1.PersonBirthdate = date.newinstance(1940, mesActual, 2);
        residente1.Tipo_Documento_Identidad__c = 'DNI';
        residente1.CIF_NIF__c = '32146871R';
        residente1.Tipo_Documento_Sanitario__c = 'NSS';
        residente1.Nuermo_Documento_Sanitario__c = '11111';
        residente1.Idioma_de_Contacto__pc = 'Castellano';
        residente1.Phone = '660085345';
        residente1.Calle__c = 'Pablo Iglesias';
        residente1.Provincia__c = 'Barcelona';
        residente1.PersonEmail = 'xgg.1990@gmail.com';
        residente1.Pais__c = 'España';
        residente1.Ciudad__c = 'Barcelona';
        residente1.Codigo_postal__c = '08016';
        residente1.IdNAV_RES__c = 'TRES55560';
        residente1.Historia_de_vida_adjunta__c = false;
        residente1.Preferencia_de_envio_de_factura__c = 'Recogida en el centro';
        insert residente1;
              
        Account ac1 = new Account();
        ac1.RecordTypeId = getRecordTypeId('Contacto Recomendador');
        ac1.Clasificacion_tipo_recomendador__c = 'B';
        ac1.Residencial__c = true;
        ac1.FirstName = 'Nombre2';
        ac1.LastName = 'Apellido2';
        ac1.Residente__c = true;
        ac1.Perfil__c = 'Autónomo';
        ac1.Sexo__c = 'Hombre';
        ac1.Estado_Civil__c = 'Soltero/a';
        ac1.PersonBirthdate = date.newinstance(1950, mesActual, 2);
        ac1.Tipo_Documento_Identidad__c = 'DNI';
        ac1.CIF_NIF__c = '55441122J';
        ac1.Tipo_Documento_Sanitario__c = 'NSS';
        ac1.Nuermo_Documento_Sanitario__c = '11111';
        ac1.Idioma_de_Contacto__pc = 'Castellano';
        ac1.Phone = '660085345';
        ac1.Calle__c = 'Pablo Iglesias';
        ac1.Provincia__c = 'Barcelona';
        ac1.PersonEmail = 'xgg2.1990@gmail.com';
        ac1.Pais__c = 'España';
        ac1.Ciudad__c = 'Barcelona';
        ac1.Codigo_postal__c = '08016';
        ac1.IdNAV_RES__c = 'TRES55560';
        ac1.Historia_de_vida_adjunta__c = false;
        ac1.Preferencia_de_envio_de_factura__c = 'Recogida en el centro';
        insert ac1;        
        
		Event e1 = new Event(
            	Subject = 'Visita',
                EventSubtype = 'Event',
            	ActivityDate = Date.newInstance(Date.today().year(), 4, 30),
                ActivityDateTime = Datetime.newInstance(Date.today().year(), 4, 30, 10, 0, 0),
                DurationInMinutes = 60,
                RecordTypeId = getRecordTypeId('Evento a Recomendador'),
				Resultado__c = 'Acción Abierta',
                //OwnerId = ac1.OwnerId,
                WhatId = ac1.Id
                //WhoId = idAccToIdCont.get(ac1.Id)
            );        
        insert e1;
        
        BatchAsignarVisita clsBatchItUpSon = new BatchAsignarVisita();
		ID idBatch = Database.executeBatch(clsBatchItUpSon, 200);
		/*
        Res_Aux__c resAux1 = new Res_Aux__c(Id = '001b000003Hb7iBAAR');
        Res_Aux__c resAux2 = new Res_Aux__c(Id = '001b000000jUJbAAAW');
        insert resAux1;
        insert resAux2;
        BatchAux clsBatchItUpSon2 = new BatchAux();
		ID idBatch2 = Database.executeBatch(clsBatchItUpSon2, 200);        
        */
        
    }
    
    private static Id getRecordTypeId(String str){
        List <RecordType>  rt = [ SELECT Id FROM RecordType WHERE Name = :str ];
        return (rt.size() > 0) ? rt.get(0).Id : null;
    }
}