SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Correo_Electronico_Generico__c</fullName>
        <label>Correo Electrónico Genérico</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>NIF_director_centro__c</fullName>
        <label>NIF director centro</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nombre_Tablet_1__c</fullName>
        <label>Nombre Tablet 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Nombre_Tablet_2__c</fullName>
        <label>Nombre Tablet 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Nombre_Tablet_3__c</fullName>
        <label>Nombre Tablet 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tableta_1__c</fullName>
        <description>Identificador del número de la tableta</description>
        <inlineHelpText>Identificador del número de la tableta</inlineHelpText>
        <label>ID Tableta 1</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tableta_2__c</fullName>
        <description>Identificador del número de la tableta</description>
        <inlineHelpText>Identificador del número de la tableta</inlineHelpText>
        <label>ID Tableta 2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tableta_3__c</fullName>
        <description>Identificador del número de la tableta</description>
        <inlineHelpText>Identificador del número de la tableta</inlineHelpText>
        <label>ID Tableta 3</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utiliza_firma_biometrica__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Utilización la firma biométrica para la generación del contrato.</description>
        <inlineHelpText>Utilizar la firma biométrica para generar el contrato?</inlineHelpText>
        <label>Utiliza firma biométrica</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>passVidsigner__c</fullName>
        <description>Contraseña de suscripción del centro a VidSigner</description>
        <label>passVidsigner</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userVidsigner__c</fullName>
        <description>User de la suscripción a VidSigner</description>
        <label>userVidsigner</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Centro</fullName>
        <active>true</active>
        <description>Residencias</description>
        <label>Centro</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Oportunidad_platform__c.object
<CustomObject>
    <fields>
        <fullName>Apellido_Avalista__c</fullName>
        <label>Apellido Avalista</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apellido_representante_legal__c</fullName>
        <label>Apellido representante legal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Autorizacion_judicial_de_internamiento__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Mediante auto de autorización judical de internamiento</inlineHelpText>
        <label>Autorización judicial de internamiento</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Centro2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Centro</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4 OR 5 OR 6 OR 7 OR 8 OR 9)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAeAAAW</value>
            </filterItems>
            <filterItems>
                <field>Account.Activo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Director_del_centro__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Zona__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>$User.ProfileId</field>
                <operation>equals</operation>
                <value>00eb0000000dTH7AAM,00eb0000000dTHC,00eb0000000dTHH,00eb0000000zplj</value>
            </filterItems>
            <filterItems>
                <field>Account.Recepcionista__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro2__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Account.ATC_Centro3__r.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Centro)</relationshipLabel>
        <relationshipName>Oportunidades3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contrato_Firmado__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campo que indica si el contrato ha sido impreso y firmado por el sistema</description>
        <label>Contrato Firmado</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DNI_Avalista__c</fullName>
        <label>DNI Avalista</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNI_Director__c</fullName>
        <formula>Centro2__r.NIF_director_centro__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DNI Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNI_Pagador__c</fullName>
        <formula>Pagador__r.CIF_NIF__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DNI Pagador</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNI_Residente__c</fullName>
        <formula>Residente__r.CIF_NIF__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DNI Residente</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNI_representante_legal__c</fullName>
        <label>DNI representante legal</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Director_Centro_First__c</fullName>
        <formula>Centro2__r.Director_del_centro__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Director Centro First</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Director_Centro_Last__c</fullName>
        <formula>Centro2__r.Director_del_centro__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Director Centro Last</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enviado_a_signar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si el PDF del contrato a sido enviado a ViDSigner</description>
        <label>Enviado a signar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ID_Doc_Firmado__c</fullName>
        <description>Identificador del documento enviado para firmar al webservice ViDSigner</description>
        <label>ID Doc Firmado</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nombre_Avalista__c</fullName>
        <label>Nombre Avalista</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nombre_propio_y_plena_capacidad_de__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>En nombre propio y con plena capacidad de obrar y obligarse</inlineHelpText>
        <label>Nombre propio y plena capacidad</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Nombre_representante_legal__c</fullName>
        <label>Nombre representante legal</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pagador_First_Name__c</fullName>
        <formula>Pagador__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pagador First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pagador_Last_Name__c</fullName>
        <formula>Pagador__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pagador Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pagador__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pagador</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAe0AAG</value>
            </filterItems>
            <filterItems>
                <field>Account.Exitus__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Pagador)</relationshipLabel>
        <relationshipName>OportunidadesPagador</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Persona_de_referencia__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>A través de la persona de referencia</inlineHelpText>
        <label>Persona de referencia</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Representate_legagal__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>A través de su representante legal</inlineHelpText>
        <label>Representate legal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Residente_First_Name__c</fullName>
        <formula>Residente__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Residente First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residente_Last_Name__c</fullName>
        <formula>Residente__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Residente Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio en etapa &apos;Visita Planificada&apos;</inlineHelpText>
        <label>Residente</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAe0AAG</value>
            </filterItems>
            <filterItems>
                <field>Account.Residente__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Exitus__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Etapa__c</field>
                <operation>equals</operation>
                <value>No ingreso, Ingreso</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Residente)</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Oportunidad</label>
    <nameField>
        <displayFormat>{YY}/{000000}</displayFormat>
        <label>Contador de Oportunidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Relacion_entre_contactos__c.object
<CustomObject>
    <fields>
        <fullName>Contacto__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contacto</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAe0AAG</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relación Familiar (Contacto)</relationshipLabel>
        <relationshipName>Relaciones_de_contactos1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Familiar_de_referencia__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Familiar de referencia</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pagador__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pagador</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAe0AAG</value>
            </filterItems>
            <filterItems>
                <field>Account.Residente__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relación Familiar (Residente)</relationshipLabel>
        <relationshipName>Relaciones_de_contactos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relación entre contactos</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Relación de contactos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relaciones entre contactos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/CalloutVidsigner.cls
/* Updates Log:
*  Alexander Shubin (09/03/2016): 
*					1) Solo crear documento y actualizar OP si el WS devuelve un documento.
*					2) Corregido el error de borrar el documento de WS
*					3) Agregar a la consulta una restricción:[..AND Familiar_de_referencia__c = true];
*  Alexander Shubin (04/04/2016): 
*					1) Agregar las respuestas de los posibles errores.
*/

global without sharing class CalloutVidsigner {
    webservice static String getDoc(String opId, String docGUI){
        Oportunidad_platform__c opl = [ SELECT Contrato_Firmado__c,  Centro2__c, Autorizacion_judicial_de_internamiento__c FROM Oportunidad_platform__c WHERE id =: opId ];
        Account acc = [ SELECT userVidsigner__c, passVidsigner__c FROM Account WHERE id =: opl.Centro2__c ];          
        String result = '';
        REST_WebService ws = new REST_WebService(acc.userVidsigner__c, acc.passVidsigner__c);
        String doc = ws.getSignedDocument(docGUI);
        System.debug('ALEX: el contenido del doc ' + doc);
        // En función del mensaje devuelto vamos a proceder a realizar una acción o otra.
        if (doc == '409'){ result = 'El documento no está firmado por completo';}
        else if(doc == '404'){ result = 'No se encuentra el documento firmado con el DocGUI especificado';}
        else if(doc == '403'){ result = 'El documento no es de esta suscripción';}
        else if(doc!='' || Test.isRunningTest()){
            Attachment at = new Attachment();
            at.Body = EncodingUtil.base64Decode(getJSONValue(doc, 'DocContent'));
            at.Name = getJSONValue(doc, 'FileName');  // add the user entered name
            at.IsPrivate = false;
            at.ParentId = opId;  // attach the pdf to the account
            if(!Test.isRunningTest()) insert at;
            result = 'OK';
            if(!Test.isRunningTest()) opl.Contrato_Firmado__c = true;
            update opl;            
        }
        return result;
    }
    
    webservice static String cancelSign(String opId, String docGUI){
        Oportunidad_platform__c opl = [ SELECT id, Enviado_a_signar__c, ID_Doc_Firmado__c, Centro2__c, 
                                         Autorizacion_judicial_de_internamiento__c 
                                        FROM Oportunidad_platform__c WHERE id =: opId ];
        Account acc = [ SELECT userVidsigner__c, passVidsigner__c FROM Account WHERE id =: opl.Centro2__c ];        
        
        REST_WebService ws = new REST_WebService(acc.userVidsigner__c, acc.passVidsigner__c);
        String result = ws.deleteDocument(docGUI, false);

        if(result==''){// doc deleted ok
            opl.Enviado_a_signar__c = false;
            opl.ID_Doc_Firmado__c = '';
            update opl;
        }
        return result;
    }

    webservice static String sendContract(String opId, String idTablet){
        
            Oportunidad_platform__c opl = [ 
                SELECT id, Name, RecordType.Name, Centro2__c, 
                  Director_Centro_First__c, Director_Centro_Last__c, DNI_Director__c,
                  Residente_First_Name__c, Residente_Last_Name__c, DNI_Residente__c, Residente__c,
                  Nombre_representante_legal__c, Apellido_representante_legal__c, DNI_representante_legal__c,
                  Nombre_propio_y_plena_capacidad_de__c, Representate_legagal__c, Persona_de_referencia__c, 
                  Nombre_Avalista__c, Apellido_Avalista__c, DNI_Avalista__c,
                  Pagador_First_Name__c, Pagador_Last_Name__c, DNI_Pagador__c, 
                  ID_Doc_Firmado__c, Enviado_a_signar__c, Pagador__c, Autorizacion_judicial_de_internamiento__c
                FROM Oportunidad_platform__c WHERE id =: opId ];
            List <Account> lacc = [ 
                   SELECT id, Name, Correo_Electronico_Generico__c, Utiliza_firma_biometrica__c, 
                    NIF_director_centro__c, Tableta_1__c, Tableta_2__c, Tableta_3__c, 
                    Nombre_Tablet_1__c, Nombre_Tablet_2__c, Nombre_Tablet_3__c, userVidsigner__c, passVidsigner__c 
                   FROM Account WHERE id =: opl.Centro2__c ];
            Account acc = (lacc.size()>0) ? lacc.get(0) : null;
            if(acc!=null){
                REST_WebService ws = new REST_WebService(acc.userVidsigner__c, acc.passVidsigner__c);
                Map<String, Object> p = new Map<String, Object>();
                
                //asignar parametros
                p.put(REST_WebService.OP_ID , opl.Id);
                p.put(REST_WebService.OP_NAME, opl.Name);
                p.put(REST_WebService.EMAIL, (acc.Correo_Electronico_Generico__c!=null) ? acc.Correo_Electronico_Generico__c : '');
                p.put(REST_WebService.TABLET_ID, idTablet);
                p.put(REST_WebService.SIGNERS , getSigners(acc, opl));        
                Map<String, String> result = (!Test.isRunningTest()) ? 
                    ws.postDocuments(p) : new Map<String,String>();
                String status = result.get(REST_WebService.STATUS);
                if(status=='OK' || Test.isRunningTest()){
                    opl.ID_Doc_Firmado__c = getJSONValue(result.get(REST_WebService.RESPONSE), 'DocGUI');            
                    opl.Enviado_a_signar__c = true;
                    try{
                        update opl;
                    } catch(Exception e){
                  System.debug('ERROR: ' + e.getMessage());
                  return 'error: ' + e.getMessage();
              }
                    
                }
                return status;
            }
            
         
        return 'error';
    }
    
    public static Map<String, Firmante> getSigners(Account acc, Oportunidad_platform__c opl){
        Map<String, Firmante> signers = new Map<String, Firmante>();
        
        /// Modalidades de firmantes
        
        if(opl.Nombre_propio_y_plena_capacidad_de__c){ //Firmantes: Residente y Avalista (si existe)
            signers.put(REST_WebService.USUARIO_REPR,
                        new Firmante(opl.Residente_First_Name__c + ' ' + opl.Residente_Last_Name__c, opl.DNI_Residente__c));            
            
        }else if(opl.Persona_de_referencia__c || opl.Autorizacion_judicial_de_internamiento__c){ //Firmantes: Familiar de referencia y Avalista (si existe)
            List <Relacion_entre_contactos__c> lrel = [SELECT id, Contacto__c 
                                                    FROM Relacion_entre_contactos__c
                                                    WHERE Residente__c  =: opl.Residente__c AND Familiar_de_referencia__c = true];
            Relacion_entre_contactos__c relacion = (lrel.size() > 0) ? lrel.get(0) : null;
            if(relacion!=null){
                List<Account> lfam = [ SELECT CIF_NIF__c, Name 
                                    FROM Account WHERE id =: relacion.Contacto__c LIMIT 1 ];
                Account familiar = (lfam.size() > 0) ? lfam.get(0) : null;
                if(familiar!=null){
                    signers.put(REST_WebService.PERSONA_REF, new Firmante( familiar.Name, familiar.CIF_NIF__c ));  
                }
            }
        }else if(opl.Representate_legagal__c) { //Firmantes: Representante Legal y Avalista (si existe)
      signers.put(REST_WebService.USUARIO_REPR, 
              new Firmante(opl.Nombre_representante_legal__c + ' ' + opl.Apellido_representante_legal__c, opl.DNI_representante_legal__c));
        }
        
        //Firmantes que se ponen solo si estan informados (Director del centro y Avalista)
        
        //Director del Centro
        if(account.Director_del_centro__c!=null){
           signers.put(REST_WebService.DIRECTOR_CENTRO, 
                       new Firmante(opl.Director_Centro_First__c + ' ' + opl.Director_Centro_Last__c, opl.DNI_Director__c));
        }
        //Avalista
        if(opl.Nombre_Avalista__c !=null){
            signers.put(REST_WebService.AVALISTA, 
                        new Firmante(opl.Nombre_Avalista__c + ' ' +opl.Apellido_Avalista__c, opl.DNI_Avalista__c));
        }
          //Pagador
        if(opl.Pagador__c!=null){
           signers.put(REST_WebService.PAGADOR, 
                    new Firmante(opl.Pagador_First_Name__c + ' ' +opl.Pagador_Last_Name__c, opl.DNI_Pagador__c));         
        }
        
        return signers;
    } 

    
    public static String getJSONValue(String jsonStr, String key){
        JSONParser parser = JSON.createParser((jsonStr!=null) ? jsonStr : '');
        String value = '';
        while (parser.nextToken()!= null) {
            if ((parser.getCurrentToken() == JSONToken.FIELD_NAME)){
                String fieldName = parser.getText();
                parser.nextToken();
                if(fieldName == key) {
                    value = parser.getText();
                }
          }
      }
        return value;  
    }
    
    
}