SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Codigo_postal__c</fullName>
        <label>Código postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fuente__c</fullName>
        <label>Fuente</label>
        <picklist>
            <picklistValues>
                <fullName>Colectivos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consejeros SARquavitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contactos Corporativos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jornadas y eventos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prensa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profesionales SARquavitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suscriptores blog</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suscriptores Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web (formularios)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webs sector</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Provincia__c</fullName>
        <label>Provincia</label>
        <picklist>
            <picklistValues>
                <fullName>A Coruña</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alacant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Álava</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albacete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Almería</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asturias</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ávila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Badajoz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bizkaia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burgos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cáceres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cádiz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cantabria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Castelló</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceuta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ciudad Real</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Córdoba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuenca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gipuzkoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Girona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guadalajara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huelva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huesca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illes Balears</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaén</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>La Rioja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Las Palmas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>León</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sexo__c</fullName>
        <label>Sexo</label>
        <picklist>
            <picklistValues>
                <fullName>Hombre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mujer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>ID_Campana__c</fullName>
        <displayFormat>CP{YY}{00000}</displayFormat>
        <externalId>true</externalId>
        <label>ID_Campaña</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Apellidos_Familiar__c</fullName>
        <label>Apellidos Familiar</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apellidos_Usuario__c</fullName>
        <label>Apellidos Usuario</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Codigo_Postal__c</fullName>
        <label>Código Postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cuenta_Bancaria__c</fullName>
        <label>Cuenta Bancaria</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNI_Usuario__c</fullName>
        <label>DNI Usuario</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Escalera__c</fullName>
        <label>Escalera</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fuente__c</fullName>
        <label>Fuente</label>
        <picklist>
            <picklistValues>
                <fullName>Consejeros SARquavitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consejeros Confide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bancs y Cajas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dirección General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presidencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contactos corporativos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profesionales SARquavitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Profesionales Confide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prensa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webs sector</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jornadas y eventos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suscritores blogs centros</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Hora_de_llamada__c</fullName>
        <label>Hora de llamada</label>
        <picklist>
            <picklistValues>
                <fullName>8 – 9h</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9 – 12h</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 – 14h</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14 – 16h</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16 – 19h</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19 – 21h</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ID_Centro__c</fullName>
        <description>Numero que identifica el centro</description>
        <label>ID Centro</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mensaje__c</fullName>
        <label>Mensaje</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Motivo_Consulta__c</fullName>
        <description>¿Que buscas? En el formulario de ¿Te puedo ayduar?&quot;</description>
        <label>Motivo Consulta</label>
        <picklist>
            <picklistValues>
                <fullName>Residencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro de día</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADOREA viviendas con servicios</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Médicos a domicilio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Empleo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nombre_Centro__c</fullName>
        <description>Nombre del centro</description>
        <label>Nombre Centro</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nombre_Familiar__c</fullName>
        <label>Nombre Familiar</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nombre_Usuario__c</fullName>
        <label>Nombre Usuario</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumCalle__c</fullName>
        <label>NumCalle</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Numero_de_formulario__c</fullName>
        <description>Numero de formulario de donde provienen los datos</description>
        <label>Numero de formulario</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Piso__c</fullName>
        <label>Piso</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provincia_Usuario__c</fullName>
        <label>Provincia Usuario</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provincia__c</fullName>
        <label>Provincia</label>
        <picklist>
            <picklistValues>
                <fullName>A Coruña</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alacant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Álava</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albacete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Almería</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asturias</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ávila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Badajoz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bizkaia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burgos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cáceres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cádiz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cantabria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Castelló</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceuta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ciudad Real</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Córdoba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuenca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gipuzkoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Girona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guadalajara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huelva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huesca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illes Balears</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaén</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>La Rioja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Las Palmas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>León</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Puerta__c</fullName>
        <label>Puerta</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sexo__c</fullName>
        <label>Sexo</label>
        <picklist>
            <picklistValues>
                <fullName>Hombre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mujer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Telefono_Usuario__c</fullName>
        <label>Teléfono Usuario</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/tgCandidatCatOtrosTest.cls
@isTest
public class tgCandidatCatOtrosTest {
    static testMethod void myUnitTest() {
   //   User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
   		Profile MarketingProfile = [select id from Profile where Name = 'Usuario de Marketing (new)'];
       	User MarketingUser = [select id from User where profileid = :MarketingProfile.id limit 1];
        String cpid = '';
        System.runAs(MarketingUser) {
            Campaign cpgn = new Campaign();
            cpgn.StartDate = Date.today().addDays(3);
       		cpgn.EndDate = Date.today().addDays(20);
        	cpgn.Name = 'Test Campaign XX';
       		insert cpgn;
            cpgn = [select id, id_campana__c from Campaign where id = :cpgn.id];
            cpid = cpgn.ID_Campana__c;
        }
        List<Lead> candidatos = new List<Lead>();
     // System.runAs(thisUser) {

        for (Integer i = 1; i < 10; ++i) {
            		Lead c = new Lead(FirstName = 'Prueba', LastName = 'Tarea Abierta', Email = 'alejandronavas@hotmail.com',Sexo__c = 'Hombre', Fuente__c = 'Web');
                c.Numero_de_formulario__c = '01';
                c.Motivo_Consulta__c = 'Residencia';
                c.Nombre_Centro__c = 'prueba1';
                c.ID_Centro__c = '000000';
                c.Provincia__c = 'Córdoba';
                c.Fuente__c = 'Web';
                c.FirstName = 'Firstname';
                c.LastName = 'Lastname';       
                c.Email = 'emailtest@test.com';
                c.Phone = '666448779';
                c.Cuenta_Bancaria__c = 'ES91 8378 1287 2189 3298';
                c.Nombre_Usuario__c = 'Nombre Usuario';
                c.Apellidos_Usuario__c ='Apellidos Usuario';
                c.Provincia_Usuario__c = 'Provincia';
              //  c.DNI_Usuario__c = '11111111P';
                c.Telefono_Usuario__c = '123456788';   
                c.Calle__c = 'Calle';
                c.NumCalle__c = '1';
                c.Piso__c = '2';
                c.Puerta__c  = '3';
                c.Escalera__c = 'B';
                c.Codigo_Postal__c = '89778';
                c.City = 'Granada';
                c.Hora_de_llamada__c = '08-09 h';
                c.Mensaje__c = 'Mensaje prueba';
                c.Nombre_Familiar__c = 'Carmen';
                c.Apellidos_Familiar__c = 'Gómez';
                c.Concepto__c = 'Concepto';
                c.ID_Campa_a__c = cpid;
                c.ID_Centro__c = '26420';
                System.debug('ID Camapaña T-T-T-Test: '+cpid);
                c.id = null;
                c.Numero_de_formulario__c = '0'+i;
                if (i == 3) c.Email = 'testclassemail2@test.com'; //probamos asociacion contacto existente
                else  c.Email = 'testclassemail'+i+'@test.com';
                c.DNI_Solicitante__c = i+'0000000J';
                c.DNI_Usuario__c = i+'1111111P';
            	candidatos.add(c);
        }
        insert candidatos;

 //     
       /*		candidatos.add(c);
       //     Lead c2 = new Lead(Firstname = 'Heyhey',Lastname = 'heyhey', email = 'hooola@hello.com', Numero_de_formulario__c = '07' );
      //      candidatos.add(c2);
            insert candidatos;
            
            
         //   Recordtype RtypeTareaCatOtros = [Select Id, Name From RecordType Where Name = 'CAT - Otros' LIMIT 1];
         	Recordtype RtypeCuentaSC = [Select Id, Name From RecordType Where Name = 'Contacto Servicios Centrales' LIMIT 1];
            Date hoy = Date.today();
           // Task t1 = [select Id, Description, RecordTypeId,createddate, Status, Subject from Task Where (RecordTypeId = :RTypeTareaCatOtros.Id ) limit 1];
         // 	Account a = [select id, recordtypeid, createddate, PersonEmail from Account where createddate = :hoy and recordtypeid = '012b0000000QFtbAAG' limit 1];
         //   System.debug('AAAAAAAAAQUIIIII EMPIEZAAAAAAAA \n'+a.PersonEmail);
//            System.debug('SUBJECT: '+t1.Subject); */

      }
}