SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoría</label>
        <picklist>
            <picklistValues>
                <fullName>Exclusive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SARqSuperior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Easy SARq</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ciudad__c</fullName>
        <label>Ciudad</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clasificacion__c</fullName>
        <label>Clasificación</label>
        <picklist>
            <picklistValues>
                <fullName>Agencias de Viajes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agencias Públicas, Empresas Públicas, Institutos Públicos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asociaciones</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ayuntamiento, Diputación, Concejalías-Equipos de Gobierno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centros Cívicos, Casales, Centros Mayores, Hogar Mayor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centros de dia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centros Dentales, Ópticas, Físios, Podólogos, Dentistas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centros de Salud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clínicas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colegios profesionales, Asesorías, Bufetes, Profesionales Liberales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Empresas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmacias y Ortopedias</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundaciones y Fundaciones tutelares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mútuas, Aseguradoras, Bancos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servicios Sociales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Universidades, Colegios, Centros de Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entidades finacieras</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instituciones públicas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Empresas privadas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundaciones y Asociaciones privadas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proveedores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BBDD adquiridas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Particulares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>...</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Clasificacion_tipo_recomendador__c</fullName>
        <inlineHelpText>Para la división Residencial</inlineHelpText>
        <label>Clasificación tipo Recomendador RES</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Codigo_postal__c</fullName>
        <label>Código postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>División</label>
        <picklist>
            <picklistValues>
                <fullName>Residencial</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Adorea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAR Domus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domiciliaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Empresa_recomendadora__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entidad recomendadora</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAd7AAG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cuentas (Empresa recomendadora)</relationshipLabel>
        <relationshipName>Cuentas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institucion_facturable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Institución facturable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provincia__c</fullName>
        <label>Provincia</label>
        <picklist>
            <picklistValues>
                <fullName>A Coruña</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alacant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Álava</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albacete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Almería</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asturias</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ávila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Badajoz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bizkaia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burgos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cáceres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cádiz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cantabria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Castelló</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceuta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ciudad Real</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Córdoba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuenca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gipuzkoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Girona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guadalajara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huelva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huesca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illes Balears</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaén</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>La Rioja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Las Palmas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>León</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Residencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sede_o_Delegaci_n__c</fullName>
        <label>Sede o Delegación</label>
        <picklist>
            <picklistValues>
                <fullName>Sede Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delegación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ninguna</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Recomendador</fullName>
        <active>true</active>
        <description>Empresa donde pertenece el recomendador</description>
        <label>Entidad Recomendadora</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/BeforeDeleteRecomendadoraTestClass.cls
/** 
* File Name:   BeforeDeleteRecomendadoraTestClass 
* Description: Classe de test del trigger BeforeDeleteRecomendadora
* Copyright:   Konozca 
* @author:     Xavier Garcia
* Modification Log 
* =============================================================== 
*Version	Date     	Author           Modification 
* 01		02/04/2015  Xavier Garcia
* =============================================================== 
**/ 
@isTest
private class BeforeDeleteRecomendadoraTestClass {
    static testMethod void myUnitTest() {
        id RecomendadoraRType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Entidad Recomendadora').getRecordTypeId();
        id RecordTypeContacto = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Contacto Recomendador').getRecordTypeId();
        Account recomendadora = new Account();
        recomendadora.RecordTypeId = RecomendadoraRType;
        recomendadora.Institucion_facturable__c = true;
        recomendadora.name = 'rec1';
        recomendadora.Sede_o_Delegaci_n__c = 'Sede Central';
        recomendadora.Type = 'Colectivo';
        recomendadora.Clasificacion__c = 'Asociaciones';
        recomendadora.Phone = '933589085';
        recomendadora.Provincia__c = 'Barcelona';
        recomendadora.Calle__c = 'Passeig de gracia';
        recomendadora.Ciudad__c = 'Barcelona';
        recomendadora.Codigo_postal__c = '08026';
        recomendadora.Residencial__c = true;
        recomendadora.Clasificacion_tipo_recomendador__c = 'B';
        triggerHelper.recursiveHelper1(true); 
        insert recomendadora;
        triggerHelper.recursiveHelper1(false); 
        
        Account contact1 = new Account();
        contact1.FirstName = 'contact1';
        contact1.LastName = 'contact1';
        contact1.RecordTypeId = RecordTypeContacto;
        contact1.Phone = '444123123222224';
        contact1.Division__c = 'Residencial';
        contact1.Categoria__c = 'Exclusive';
        contact1.Institucion_facturable__c = true;
        contact1.Residencial__c = true;
        contact1.Clasificacion_tipo_recomendador__c = 'A';
        contact1.Idioma_de_Contacto__pc = 'Castellano';
        contact1.Empresa_recomendadora__c = recomendadora.id;      
        insert contact1;
        
        delete recomendadora;
        
    }

	
}