SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Apellido_2__c</fullName>
        <inlineHelpText>Campo obligatorio para residentes. Recomendable en el resto de contactos.</inlineHelpText>
        <label>Apellido 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIF_NIF__c</fullName>
        <label>CIF/NIF</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Calle__c</fullName>
        <label>Calle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ciudad__c</fullName>
        <label>Ciudad</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clasificacion__c</fullName>
        <label>Clasificación</label>
        <picklist>
            <picklistValues>
                <fullName>Agencias de Viajes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agencias Públicas, Empresas Públicas, Institutos Públicos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asociaciones</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ayuntamiento, Diputación, Concejalías-Equipos de Gobierno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centros Cívicos, Casales, Centros Mayores, Hogar Mayor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centros de dia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centros Dentales, Ópticas, Físios, Podólogos, Dentistas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centros de Salud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clínicas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colegios profesionales, Asesorías, Bufetes, Profesionales Liberales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Empresas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Farmacias y Ortopedias</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundaciones y Fundaciones tutelares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mútuas, Aseguradoras, Bancos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servicios Sociales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Universidades, Colegios, Centros de Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entidades finacieras</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Instituciones públicas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Empresas privadas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundaciones y Asociaciones privadas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proveedores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BBDD adquiridas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Particulares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>...</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Clasificacion_tipo_recomendador__c</fullName>
        <inlineHelpText>Para la división Residencial</inlineHelpText>
        <label>Clasificación tipo Recomendador RES</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Codigo_postal__c</fullName>
        <label>Código postal</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Empresa_recomendadora__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entidad recomendadora</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAd7AAG</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cuentas (Empresa recomendadora)</relationshipLabel>
        <relationshipName>Cuentas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estado_Civil__c</fullName>
        <label>Estado Civil</label>
        <picklist>
            <picklistValues>
                <fullName>Soltero/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divorciado/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Viudo/a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Casado/a</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fecha_apertura__c</fullName>
        <label>Fecha apertura</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nuermo_Documento_Sanitario__c</fullName>
        <label>Número Documento Sanitario</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pais__c</fullName>
        <label>País</label>
        <picklist>
            <picklistValues>
                <fullName>España</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>U.E.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No U.E.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Perfil__c</fullName>
        <inlineHelpText>Campo obligatorio para residentes</inlineHelpText>
        <label>Perfil</label>
        <picklist>
            <picklistValues>
                <fullName>Autónomo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dependiente</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provincia__c</fullName>
        <label>Provincia</label>
        <picklist>
            <picklistValues>
                <fullName>A Coruña</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alacant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Álava</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albacete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Almería</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asturias</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ávila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Badajoz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bizkaia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burgos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cáceres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cádiz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cantabria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Castelló</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceuta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ciudad Real</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Córdoba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuenca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gipuzkoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Girona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guadalajara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huelva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huesca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illes Balears</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaén</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>La Rioja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Las Palmas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>León</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Residencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sexo__c</fullName>
        <label>Sexo</label>
        <picklist>
            <picklistValues>
                <fullName>Hombre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mujer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Documento_Identidad__c</fullName>
        <label>Tipo Documento Identidad</label>
        <picklist>
            <picklistValues>
                <fullName>DNI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pasaporte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documento de residencia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Documento_Sanitario__c</fullName>
        <label>Tipo Documento Sanitario</label>
        <picklist>
            <picklistValues>
                <fullName>NSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MUFACE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISFAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Otros</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zona_comercial__c</fullName>
        <inlineHelpText>Informar como mínimo una zona comercial si no es una sede central</inlineHelpText>
        <label>Zona Comercial RES</label>
        <picklist>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Este</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mallorca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navarra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oeste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Occidental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Oriental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zaragoza</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Zona_Comercial__c</fullName>
        <label>Zona Comercial</label>
        <picklist>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Este</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mallorca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navarra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oeste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Occidental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Oriental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zaragoza</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/testFelicitaciones.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class testFelicitaciones {

    static testMethod void testBatch() {

	    Account a1 = new Account();
        a1.FirstName = '1';
        a1.LastName = 'cliente1 apell';
        a1.PersonEmail = 'test@test.com';
        a1.Apellido_2__c = 'apell';
        a1.Perfil__c = 'Autónomo';
        a1.Idioma_de_Contacto__pc = 'Catalan';
        a1.Residente__c = true;
        a1.Phone = '523423423455';
        a1.RecordTypeId = '012b0000000QAe0AAG';
        a1.CIF_NIF__c = '32146871R';
        a1.Tipo_Documento_Sanitario__c = 'NCS';
        a1.Nuermo_Documento_Sanitario__c = '111';
        a1.Estado_Civil__c = 'Casado/a';
        a1.Sexo__c = 'Hombre';
        a1.Tipo_Documento_Identidad__c = 'DNI';
        a1.CIF_NIF__c = '47794178V';
        a1.Calle__c = 'Carrer de buenos aires 34';
        a1.Ciudad__c = 'Barcelona';
        a1.PersonBirthdate = Date.today().addYears(-1).addDays(7);
        a1.Codigo_postal__c  = '08036';
        insert a1;
        
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
    	
    	System.runAs ( thisUser ) {
	        User uAux = [Select Id, Zona_comercial__c, ProfileId From User LIMIT 1];
			uAux.Zona_comercial__c = 'Barcelona';
			uAux.UserRoleId = '00Eb0000000h3VX';
			update uAux;
    	}
		
		Account empRec = new Account();
		empRec.RecordTypeId = '012b0000000QAd7AAG';
		empRec.Name = 'rec1 rec1';
		empRec.Phone = '412321233144';
		empRec.Clasificacion__c = 'otros';
		empRec.Calle__c = 'C/ Madrid';
		empRec.Ciudad__c = 'Barcelona';
		empRec.Codigo_postal__c = '02805';
		empRec.Fecha_apertura__c = Date.today().addYears(-1).addDays(7);
		empRec.Pais__c = 'España';
		empRec.Provincia__c = 'Barcelona';
		empRec.Zona_Comercial__c = 'Barcelona';
        empRec.Residencial__c = true;
		empRec.Clasificacion_tipo_recomendador__c = 'A';
		insert empRec;
		
        Account rec = new Account();
		rec.RecordTypeId = '012b0000000QCbtAAG';
        rec.personemail = 'test@test.com';
		rec.FirstName = 'rc1';
		rec.LastName = 'rec1 rec1';
		rec.Phone = '412321233144';
		rec.Empresa_recomendadora__c = empRec.Id;
        rec.Residencial__c = true;
		rec.PersonBirthdate = Date.today().addYears(-1).addDays(7);
		rec.Activo__c = true;
		rec.Clasificacion_tipo_recomendador__c = 'A';
		insert rec;
        
        scheduleBatch m = new scheduleBatch();
		String sch = '20 30 8 10 2 ?';
		String jobID = system.schedule('Merge Job', sch, m);
		
		Test.StartTest();
		Felicitaciones fels = new Felicitaciones();
		ID batchprocessid = Database.executeBatch(fels);
		Test.StopTest();
	
    }
}