SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Director_del_centro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio si el centro está Activo</inlineHelpText>
        <label>Director del centro</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Director Centro</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Director_centro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>División</label>
        <picklist>
            <picklistValues>
                <fullName>Residencial</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Adorea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAR Domus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domiciliaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IdNAV__c</fullName>
        <description>Identificador de Navision</description>
        <externalId>true</externalId>
        <label>IdNAV</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Residencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tipo_centro__c</fullName>
        <label>Tipo centro</label>
        <picklist>
            <picklistValues>
                <fullName>Público</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Privado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixto</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zona_Comercial_del__c</fullName>
        <label>Zona Comercial Centro</label>
        <picklist>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Este</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mallorca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navarra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oeste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Occidental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Oriental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zaragoza</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Centro</fullName>
        <active>true</active>
        <description>Residencias</description>
        <label>Centro</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Centros_NOC__c.object
<CustomObject>
    <description>Centros que comparten una misma NOC</description>
    <fields>
        <fullName>Activo__c</fullName>
        <label>Activo</label>
        <picklist>
            <picklistValues>
                <fullName>Si</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Centro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Centro</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAeAAAW</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Centros NOCs</relationshipLabel>
        <relationshipName>Centros_NOCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Descuento__c</fullName>
        <label>Descuento</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>División</label>
        <picklist>
            <picklistValues>
                <fullName>Residencial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adorea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAR Domus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domiciliaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEX</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>NOC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOC</label>
        <referenceTo>NOC__c</referenceTo>
        <relationshipLabel>Centros / Servicios NOCs Residencial</relationshipLabel>
        <relationshipName>Centros_NOCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Precio__c</fullName>
        <label>Precio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tipo_Estancia_2__c</fullName>
        <label>Tipo Estancia</label>
        <picklist>
            <picklistValues>
                <fullName>Permanente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporal</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Tipo_Servicio_2__c</fullName>
        <label>Tipo Servicio</label>
        <picklist>
            <picklistValues>
                <fullName>Centro de Día</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro de Noche</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convalecencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fijo Discontinuo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital de Día</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paleativo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residencial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Respiro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UTC</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Zona_Comercial_2__c</fullName>
        <label>Zona Comercial</label>
        <picklist>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Este</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mallorca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navarra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oeste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Occidental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Oriental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zaragoza</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Centros/Servicios NOC</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Centros NOC</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Centros NOCs</pluralLabel>
    <recordTypes>
        <fullName>Centros_Servicios_NOC_mejorada</fullName>
        <active>true</active>
        <label>Centros/Servicios NOC (mejorada)</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/NOC__c.object
<CustomObject>
    <fields>
        <fullName>Centro__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>En caso que aplique a un centro en concreto</inlineHelpText>
        <label>Centro</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAeAAAW</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NOCs</relationshipLabel>
        <relationshipName>NOCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Descuento__c</fullName>
        <formula>1-(Precio_propuesto__c  /   Precio_actual__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Descuento</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Descuento_permanente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Descuento permanente</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>División</label>
        <picklist>
            <picklistValues>
                <fullName>Residencial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adorea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAR Domus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domiciliaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Duracion_del_descuento__c</fullName>
        <inlineHelpText>Sólo para la división Residencial</inlineHelpText>
        <label>Duración del descuento en días</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estado_Flujo__c</fullName>
        <label>Estado Flujo</label>
        <picklist>
            <picklistValues>
                <fullName>Pendiente</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aprobado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rechazado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fecha_fin__c</fullName>
        <inlineHelpText>Periodo en el que puede utilizarse la NOC</inlineHelpText>
        <label>Fecha fin</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fecha_inicio__c</fullName>
        <inlineHelpText>Periodo en el que puede utilizarse la NOC</inlineHelpText>
        <label>Fecha inicio</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Residencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residencial</label>
        <type>Checkbox</type>
    </fields>
    <label>NOC</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NOCs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/TestTriggerVisibilidadNOC.cls
/** 
* File Name:   TriggerVisibilidadNOC 
* Description: Añade la visibilidad de centros y zona comercial a la NOC
* Copyright:   Konozca 
* @author:     Hector Mañosas
* Modification Log 
* =============================================================== 
*Date     		Author          Modification 
* 22/07/2014 	HManosas		
* =============================================================== 
**/

@isTest
private class TestTriggerVisibilidadNOC {

    static testMethod void myUnitTest() {
                
        //Creamos una Account de tipo Centro
        Account centro1 = new Account();
        centro1.Name = 'Centro1';
        //centro1.RecordTypeId = '012b0000000QAeAAAW';     //Centro   getRecordTypeId
        centro1.RecordTypeId = getRecordTypeId('Centro');
        //centro1.RecordTypeId = getRecordTypeId('Centro');
        centro1.Phone = '442342343244';
        centro1.Activo__c = true;
        centro1.Director_del_centro__c = '005b0000001JTCKAA4';
        centro1.Division__c = 'Residencial';
        centro1.Zona_Comercial_del__c = 'Barcelona';
        centro1.IdNAV__c = 'CANBUXERES';
        centro1.Tipo_centro__c = 'Mixto';
        triggerHelper.recursiveHelper1(true);
        insert centro1;
        triggerHelper.recursiveHelper1(false);
        
        //Creamos una nueva Account de tipo Centro
        Account centro2 = new Account();
        centro2.Name = 'Centro2';
        //centro2.RecordTypeId = '012b0000000QAeAAAW';      //Centro  
        centro2.RecordTypeId = getRecordTypeId('Centro');
        centro2.Phone = '442342343244';
        centro2.Activo__c = true;
        centro2.Director_del_centro__c = '005b0000001JTCKAA4';
        centro2.Division__c = 'Residencial';
        centro2.Zona_Comercial_del__c = 'Centro';
        centro2.IdNAV__c = 'MONTMARTI';
        triggerHelper.recursiveHelper1(true);
        insert centro2;
        triggerHelper.recursiveHelper1(false);
        
        //Creamos una NOC de tipo Convenio
        NOC__c noc1 = new NOC__c();
        //noc1.RecordTypeId = '012b0000000QBd0AAG'; //NOC12 Convenios
        noc1.RecordTypeId = getRecordTypeId('NOC 12 Convenios');
        noc1.Name = 'noc1';
        noc1.Estado_Flujo__c = 'Aprobado';        
        noc1.Fecha_inicio__c = Date.today().addDays(-30);
        noc1.Fecha_fin__c = Date.today().addDays(30);
        noc1.Descuento_permanente__c = true;
        noc1.Residencial__c = true;
        //noc1.Duracion_del_descuento__c = 30;
        triggerHelper.recursiveHelper1(true);       
        insert noc1;
        triggerHelper.recursiveHelper1(false);
        
        RecordType rtCNoc1 = [SELECT Id,Name FROM RecordType WHERE Developername='Centros_Servicios_NOC_mejorada']; 
        
        //Creamos un centroNOC para la NOC2 Convenio
        Centros_NOC__c cNoc1 = new Centros_NOC__c();
        cNoc1.RecordTypeId = rtCNoc1.Id;
        cNoc1.NOC__c = noc1.Id;
        cNoc1.Centro__c = null;
        cNoc1.Zona_Comercial_2__c = null;
        cNoc1.Division__c = 'Residencial';
        cNoc1.Precio__c = 10;
        cNoc1.Tipo_Servicio_2__c = 'Residencial';
        cNoc1.Tipo_Estancia_2__c = 'Permanente';
        cNoc1.Tipo_Ocupacion_2__c = 'HD';
        cNoc1.Grado__c = 'Grado1';        
        insert cNoc1;
        
        //Creamos un nuevo centroNOC para la NOC2 Convenio
        Centros_NOC__c cNoc2 = new Centros_NOC__c();
        cNoc2.RecordTypeId = rtCNoc1.Id;
        cNoc2.NOC__c = noc1.Id;
        cNoc2.Centro__c = null;
        cNoc2.Zona_Comercial_2__c = null;
        cNoc2.Division__c = 'Residencial';
        cNoc2.Precio__c = 10;
        cNoc2.Tipo_Servicio_2__c = 'Residencial';
        cNoc2.Tipo_Estancia_2__c = 'Permanente';
        cNoc2.Tipo_Ocupacion_2__c = 'HD';
        cNoc2.Grado__c = 'Grado2';
		
        insert cNoc2;
        
        //Actualizamos la Zona Comercial del centro NOC
        cNoc1.Zona_Comercial_2__c = 'Barcelona';
        cNoc1.Division__c = null;
        update cNoc1;
        
        //Actualizamos el centro del centro NOC
        cNoc1.Centro__c = centro1.Id;
        cNoc1.Zona_Comercial_2__c = null;
        update cNoc1;
        
        //Creamos un nuevo centroNOC para la NOC2 Convenio
        Centros_NOC__c cNoc3 = new Centros_NOC__c();
        cNoc3.RecordTypeId = rtCNoc1.Id;
        cNoc3.NOC__c = noc1.Id;
        cNoc3.Centro__c = centro2.Id;
        cNoc3.Zona_Comercial_2__c = null;
        cNoc3.Division__c = null;
        cNoc3.Descuento__c = 25;
        cNoc3.Tipo_Servicio_2__c = 'Residencial';
        cNoc3.Tipo_Estancia_2__c = 'Permanente';
        cNoc3.Tipo_Ocupacion_2__c = 'HD';
        cNoc3.Grado__c = 'Grado2';        
        insert cNoc3;             
        
        //Borramos el centro NOC
        delete cNoc1;        
        
    }
    
    public static String getRecordTypeId(String name){
        List<RecordType> rt = [ Select id FROM RecordType WHERE Name =: name LIMIT 1 ];
        return (rt.size()> 0) ? rt.get(0).id : null;
    }
}