SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Residente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residente</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Oportunidad_platform__c.object
<CustomObject>
    <fields>
        <fullName>Etapa__c</fullName>
        <label>Etapa</label>
        <picklist>
            <picklistValues>
                <fullName>Información / Visita</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pendiente visita</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Visita Planificada / Espontánea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentado Plan Personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preingreso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ingreso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No ingreso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abierta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negociación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stand-by</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerrada ganada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerrada perdida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerrada por el sistema</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Motivo_de_Alta_Comercial__c</fullName>
        <label>Motivo de Alta Comercial</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio en etapa &apos;Visita Planificada&apos;</inlineHelpText>
        <label>Residente</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAe0AAG</value>
            </filterItems>
            <filterItems>
                <field>Account.Residente__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Exitus__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Etapa__c</field>
                <operation>equals</operation>
                <value>No ingreso, Ingreso</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Residente)</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Oportunidad</label>
    <nameField>
        <displayFormat>{YY}/{000000}</displayFormat>
        <label>Contador de Oportunidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Res_Aux__c.object
<CustomObject>
    <fields>
        <fullName>id__c</fullName>
        <label>id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Res Aux</label>
    <nameField>
        <label>Nombre de Res Aux</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Res Aux</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/residentes_to_update__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>id__c</fullName>
        <label>id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>residentes_to_update</label>
</CustomObject>

SAR Blai Sandbox/src/classes/BatchAux.cls
global class BatchAux implements Database.Batchable<SObject>, Database.AllowsCallouts{
    
    global String glstrQuery;
    global Map<Id, List<Oportunidad_platform__c>> mapResOps; //oportunidades asociadas al residente
    global List<String> idsResidentes;
    global List <residentes_to_update__c> resVerificar;
	
    
    global BatchAux(){
        
        mapResOps = new Map<Id, List<Oportunidad_platform__c>>();
        idsResidentes = new List<String>();
        resVerificar = new List <residentes_to_update__c>();
        for(Res_Aux__c r : [SELECT id__c FROM Res_Aux__c]){
            idsResidentes.add(r.id__c);
        }
        for(Oportunidad_platform__c op : [ SELECT Id, Residente__c, Motivo_de_Alta_Comercial__c, Etapa__c 
                                           FROM Oportunidad_platform__c 
                                           WHERE Residente__c IN :idsResidentes ORDER BY CreatedDate ASC]){
            addOp(op);
        }
        
        System.debug('mapResOps:');
        System.debug(mapResOps);
        glstrQuery = 'SELECT Id FROM Account WHERE Id IN :idsResidentes';
    }
    

    
	//Funció start del batch
    global Database.QueryLocator start(Database.BatchableContext bcMain) {
        return Database.getQuerylocator(glstrQuery);
    }  
    
    global void execute(Database.BatchableContext bcMain, List<Account> lstResidentes) {
        
        for(Account ac : lstResidentes){
            List<Oportunidad_platform__c> opsAsoc = mapResOps.get(ac.Id);
            if(opsAsoc!=null){
                Oportunidad_platform__c lastOp = opsAsoc.get(opsAsoc.size()-1);
                if( lastOp.Motivo_de_Alta_Comercial__c==null || lastOp.Motivo_de_Alta_Comercial__c=='') {
                    resVerificar.add(new residentes_to_update__c(Id__c = ac.Id, Name = ac.Id));
                }
            }
        }
        insert resVerificar;
    }    
    
    global void finish(Database.BatchableContext bcMain){}    
    
    private String generateRandomId(){
        String hashString = '1000' + String.valueOf(Datetime.now().formatGMT('yyyy-MM-dd HH:mm:ss.SSS'));
        Blob hash = Crypto.generateDigest('MD5', Blob.valueOf(hashString));
        String hexDigest = EncodingUtil.convertToHex(hash);
        return hexDigest;       
    }    
    
    private void addOp(Oportunidad_platform__c o){
        List<Oportunidad_platform__c> lop;
        if(mapResOps.get(o.Residente__c)==null){
            lop = new List<Oportunidad_platform__c>();
        }else{
            lop = mapResOps.get(o.Residente__c);
        }
        
        lop.add(new Oportunidad_platform__c(Id = o.Id, 
                                            Etapa__c = o.Etapa__c,
                                            Residente__c = o.Residente__c, 
                                            Motivo_de_Alta_Comercial__c = o.Motivo_de_Alta_Comercial__c));
        mapResOps.put(o.Residente__c, lop);        
    }    
}