SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Aniversario_apertura__c</fullName>
        <formula>DATEVALUE( TEXT( YEAR ( TODAY() ) ) &amp; &quot;-&quot; &amp;
    TEXT( MONTH ( Fecha_apertura__c) ) &amp; &quot;-&quot; &amp;
    TEXT( DAY ( Fecha_apertura__c) ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aniversario_apertura</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residente</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Oportunidad_platform__c.object
<CustomObject>
    <fields>
        <fullName>Etapa__c</fullName>
        <label>Etapa</label>
        <picklist>
            <picklistValues>
                <fullName>Información / Visita</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pendiente visita</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Visita Planificada / Espontánea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentado Plan Personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preingreso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ingreso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No ingreso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abierta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negociación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stand-by</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerrada ganada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerrada perdida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerrada por el sistema</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Residente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Campo obligatorio en etapa &apos;Visita Planificada&apos;</inlineHelpText>
        <label>Residente</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR 4)</booleanFilter>
            <filterItems>
                <field>Account.RecordType.Id</field>
                <operation>equals</operation>
                <value>012b0000000QAe0AAG</value>
            </filterItems>
            <filterItems>
                <field>Account.Residente__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.Exitus__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>$Source.Etapa__c</field>
                <operation>equals</operation>
                <value>No ingreso, Ingreso</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades (Residente)</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Oportunidad</label>
    <nameField>
        <displayFormat>{YY}/{000000}</displayFormat>
        <label>Contador de Oportunidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/Felicitaciones.cls
global class Felicitaciones implements Database.Batchable<sObject>, Database.Stateful {

   global final String Query;

   global Felicitaciones(){
        Query = 'Select Id, Name, OwnerId, PersonBirthdate, RecordTypeId, Residente__c, Aniversario_apertura__c From Account Where (((RecordTypeId = \'012b0000000QAe0AAG\' and Residente__c = true) or RecordTypeId = \'012b0000000QCbtAAG\') and PersonBirthdate > NEXT_N_DAYS:6 and PersonBirthdate = NEXT_N_DAYS:7)  or (RecordTypeId = \'012b0000000QAd7AAG\' and Aniversario_apertura__c > NEXT_N_DAYS:6 and Aniversario_apertura__c = NEXT_N_DAYS:7)';
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(Query);
   }

    //envia mensajes a los propietarios de los recomendadores y residentes que hacen años dentro de una setmana
   global void execute(Database.BatchableContext BC, List<Account> lacc){
      List<Id> idResidentes = new List<Id>();
        for(Account a : lacc){
            if(a.RecordTypeId == '012b0000000QAe0AAG' && a.Residente__c == true) idResidentes.add(a.Id);
        }
        List<Oportunidad_platform__c> ops = [Select Id, OwnerId, Etapa__c, Residente__c FROM Oportunidad_platform__c WHERE Residente__c In :idResidentes];
      
      List<User> lus = [Select Id, Email From User];
      List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
      for(Account a : lacc){
        boolean b = false;
            Id owner = null;
            if(a.RecordTypeId == '012b0000000QAe0AAG' && a.Residente__c == true) {
                Boolean enc = false;
                for(integer i = 0; i < ops.Size() && !enc; ++i) {
                    if(ops[i].Residente__c == a.Id && ops[i].Etapa__c == 'Ingreso') {
                        enc = true;
                        owner = ops[i].OwnerId;
                    } 
                }
            }
            else owner = a.OwnerId; 
            if(owner != null) {
                  for(integer i = 0; i < lus.Size() && !b; ++i) {
                    if(lus[i].Id == owner) {
                        b = true;
                        try {
                            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
                            mail.setToAddresses(new List<String>{lus[i].Email, 'sergi.aguilar@konozca.com'}); 
                            mail.setSubject('Recordatorio de aniversario'); 
                            String body = '';
                            if(a.RecordTypeId == '012b0000000QAd7AAG') body = 'Apreciado/a,\n\n'+ 'La fecha de aperture de la entidad recomendadora '+ a.Name +' (https://sarquavitae.my.salesforce.com/'+a.Id+') fue el ' +  a.Aniversario_apertura__c.day() + '-' + a.Aniversario_apertura__c.month() + '-' + a.Aniversario_apertura__c.year()  + ' por lo que se acerca su aniversario. \n' +'Recuerda contactar para felicitarle.\n\n' +'Un cordial saludo,'; 
                            else body = 'Apreciado/a,\n\n'+ 'La fecha de nacimiento de '+ a.Name +' (https://sarquavitae.my.salesforce.com/'+a.Id+') fue el ' +  a.PersonBirthdate.day() + '-' + a.PersonBirthdate.month() + '-' + a.PersonBirthdate.year()  + ' por lo que se acerca su aniversario. \n' +'Recuerda contactar para felicitarle.\n\n' +'Un cordial saludo,'; 
                            mail.setPlainTextBody(body); 
                            emails.add(mail);
                        }
                        catch(Exception e) {
                            system.debug(e);
                        }
                    }
                }
            }
      }
     // if(!Test.isRunningTest()) Messaging.sendEmail(emails);
    }

   global void finish(Database.BatchableContext BC){
   }
   
}