SAR Blai Sandbox/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Baja__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Baja</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Capacidad_Teorica__c</fullName>
        <label>Capacidad Teórica</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoría</label>
        <picklist>
            <picklistValues>
                <fullName>Exclusive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SARqSuperior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Easy SARq</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Clasificacion_tipo_recomendador__c</fullName>
        <inlineHelpText>Para la división Residencial</inlineHelpText>
        <label>Clasificación tipo Recomendador RES</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>División</label>
        <picklist>
            <picklistValues>
                <fullName>Residencial</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Adorea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAR Domus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Domiciliaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teleasistencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fecha_apertura__c</fullName>
        <label>Fecha apertura</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Institucion_facturable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Institución facturable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provincia__c</fullName>
        <label>Provincia</label>
        <picklist>
            <picklistValues>
                <fullName>A Coruña</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alacant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Álava</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albacete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Almería</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asturias</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ávila</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Badajoz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bizkaia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burgos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cáceres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cádiz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cantabria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Castelló</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceuta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ciudad Real</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Córdoba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cuenca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gipuzkoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Girona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Granada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guadalajara</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huelva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Huesca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illes Balears</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jaén</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>La Rioja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Las Palmas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>León</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Residencial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Residencial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zona_comercial__c</fullName>
        <inlineHelpText>Informar como mínimo una zona comercial si no es una sede central</inlineHelpText>
        <label>Zona Comercial RES</label>
        <picklist>
            <picklistValues>
                <fullName>Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Este</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mallorca</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navarra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norte</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oeste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Occidental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sur Oriental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Valencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zaragoza</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <recordTypes>
        <fullName>Recomendador</fullName>
        <active>true</active>
        <description>Empresa donde pertenece el recomendador</description>
        <label>Entidad Recomendadora</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Baja__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Baja cont</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Tarea_CAT_Otros</fullName>
        <active>true</active>
        <label>CAT - Otros</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/BeforeTaskTestClass.cls
/** 
* File Name:   BeforeTaskTestClass 
* Description: Classe test del trigger BeforeTask
* Copyright:   Konozca 
* @author:     Xavier Garcia
* Modification Log 
* =============================================================== 
*Version	Date     	Author           Modification 
* 01		11/02/2014  Xavier Garcia
* =============================================================== 
**/ 
@isTest
private class BeforeTaskTestClass {
	static testMethod void myUnitTest() {
        date avui = date.today();
        integer mesActual = avui.month();
        
       /* Account a = new Account();
        a.RecordTypeId = '012b0000000QAe0';
        a.FirstName = 'Cliente';
        a.LastName = 'Comodín';
        a.PersonEmail = 'test@test.test';
        a.Phone = '939999999';
        a.Baja__c = true;
        triggerHelper.recursiveHelper1(true);
        insert a;
        triggerHelper.recursiveHelper1(true);*/
        
        
         //Crear Entidad Recomendadora
        Account centrorec = new Account();
        centrorec.Name = 'Recomenadora1';
        centrorec.RecordTypeId = '012b0000000QAd7AAG';
        centrorec.Zona_Comercial__c = 'Barcelona';
        centrorec.Phone = '444123123222224';
        centrorec.Activo__c = true;
        centrorec.Zona_Comercial__c = 'Barcelona';
        centrorec.Division__c = 'Residencial';
        centrorec.Categoria__c = 'Exclusive';
        centrorec.Institucion_facturable__c = true;
        centrorec.Fecha_apertura__c = System.today().addDays(-15);
        centrorec.Capacidad_Teorica__c = 100;
        centrorec.Baja__c = true;
        centrorec.Residencial__c = true;
        centrorec.Clasificacion_tipo_recomendador__c = 'A';
        centrorec.Provincia__c = 'Barcelona';
        triggerHelper.recursiveHelper1(true);        
        insert centrorec;
        triggerHelper.recursiveHelper1(false);
        
        //Crear Cuenta Recomendador
        Account contacto = new Account();
       	contacto.FirstName = 'Contacto1';
        contacto.LastName = 'Contacto1';
        contacto.RecordTypeId = '012b0000000QCbt';
        contacto.Idioma_de_Contacto__pc = 'Castellano';
        contacto.Clasificacion_tipo_recomendador__c = 'A';
        contacto.Residencial__c = true;
        contacto.Baja__c = true;
        contacto.Phone = '660085378';
        triggerHelper.recursiveHelper1(true);        
        insert contacto;
        triggerHelper.recursiveHelper1(false);
        
        //Crear contacto
        /*Contact cont = new Contact();
        cont.AccountId = contacto.Id;
        triggerHelper.recursiveHelper1(true);        
       	insert cont;
        triggerHelper.recursiveHelper1(false);*/
        
        
        /*Recordtype RtypeTareaCatOtros = [Select Id, Name From RecordType Where DeveloperName = 'Tarea_CAT_Otros' LIMIT 1];
        Task tascaOtros = new Task();
        tascaOtros.RecordTypeId = RtypeTareaCatOtros.id;
        // tasca.WhoId = contacto.Id;
        tascaOtros.WhatId = null;
        tascaOtros.OwnerId = '005b0000000kj7H';
        tascaOtros.Subject = 'Llamada';
        tascaOtros.ActivityDate = avui.addDays(5);
        tascaOtros.Status = 'Completada';
        tascaOtros.Priority = 'Normal';       
        insert tascaOtros;*/
        
		Recordtype RtypeTareaRecomendador = [Select Id, Name From RecordType Where Name = 'Tarea Recomendador' LIMIT 1];
        
        try {
            Task tasca = new Task();
            tasca.RecordTypeId = RtypeTareaRecomendador.id;
           // tasca.WhoId = contacto.Id;
            tasca.WhatId = centrorec.Id;
            tasca.OwnerId = '005b0000000kj7H';
            tasca.Subject = 'Llamada';
            tasca.ActivityDate = avui.addDays(5);
            tasca.Status = 'Pendiente';
            tasca.Priority = 'Normal';       
            insert tasca;
            throw new MyException ('El trigger debería lanzar una excepción');
        }
        catch(Exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains('Ni el contacto recomendador ni la empresa recomendadora pueden tener seleccionado el campo baja.') ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
        }  
    }
}