SAR Blai Sandbox/src/objects/Oportunidad_platform__c.object
<CustomObject>
    <fields>
        <fullName>Canal__c</fullName>
        <label>Canal</label>
        <picklist>
            <picklistValues>
                <fullName>Chat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institución</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Llamada al centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Llamada desde el centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Llamada emitida del CAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Llamada recibida al CAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registro vía Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visita espontánea</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Etapa__c</fullName>
        <label>Etapa</label>
        <picklist>
            <picklistValues>
                <fullName>Información / Visita</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pendiente visita</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Visita Planificada / Espontánea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Presentado Plan Personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preingreso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ingreso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No ingreso</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abierta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negociación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stand-by</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerrada ganada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerrada perdida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cerrada por el sistema</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fecha_finalizacion__c</fullName>
        <inlineHelpText>Residencial: Campo obligatorio si el tipo de estancia es &apos;Temporal&apos;</inlineHelpText>
        <label>Fecha finalización</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fecha_prevista_de_ingreso__c</fullName>
        <inlineHelpText>Campo obligatorio en Etapa= &apos;Preingreso&apos;</inlineHelpText>
        <label>Fecha prevista de ingreso</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IBAN__c</fullName>
        <description>Número de la cuenta corriente formado por dos letras y 22 dígitos</description>
        <inlineHelpText>Residencial: Campo obligatorio en Etapa= &apos;Ingreso&apos; / &apos;Cerrada ganada&apos;</inlineHelpText>
        <label>IBAN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nombre_Avalista__c</fullName>
        <label>Nombre Avalista</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nombre_propio_y_plena_capacidad_de__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>En nombre propio y con plena capacidad de obrar y obligarse</inlineHelpText>
        <label>Nombre propio y plena capacidad</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pagina_web__c</fullName>
        <inlineHelpText>Campo obligatorio si Prescriptor = Internet</inlineHelpText>
        <label>Página web</label>
        <picklist>
            <picklistValues>
                <fullName>Infoelder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inforesidencias</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Sarquavitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WOHNEN IM ALTER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Te Acompaña</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Precio_Colgantes__c</fullName>
        <inlineHelpText>A partir del 2º usuario</inlineHelpText>
        <label>Precio Colgantes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Precio_sin_colgante__c</fullName>
        <label>Precio sin colgante</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Procedencia__c</fullName>
        <label>Procedencia</label>
        <picklist>
            <picklistValues>
                <fullName>Centro Sarquavitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clientes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colectivo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institución</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jornadas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medios de comunicación</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Sarquavitae</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prescriptor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vecindad</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Regimen__c</fullName>
        <inlineHelpText>Campo obligatorio en Etapa= &apos;Ingreso&apos;</inlineHelpText>
        <label>Régimen</label>
        <picklist>
            <picklistValues>
                <fullName>Residencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UTC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fin de Semana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinuo</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Financiacion__c</fullName>
        <inlineHelpText>Campo obligatorio en Etapa= &apos;Preingreso&apos;</inlineHelpText>
        <label>Tipo de Financiación</label>
        <picklist>
            <picklistValues>
                <fullName>ARTECAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ayuntamiento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ayuntamiento Privado Barcelona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonos Consellería</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caja Sol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catsalut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convenio internacional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSS CA Madrid - Co Financiados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSS CA Madrid - Financiados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diputación de Málaga</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diputación de Toledo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diputación de Valencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diputación Foral de Alaba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diputación Foral de Bizkaia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diputación Foral Guipúzcoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E.R.A.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entidades de seguros libres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FERTECAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundació Balear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fundación Andaluza</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Generalitat de Valencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GOBIERNO CANTABRIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IASS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IASS Gobierno de Aragón</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICASS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IMSERSO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Junta de Castilla La Mancha</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Junta de Extremadura</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mutualidades públicas concertades</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Privado</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_de_pago__c</fullName>
        <inlineHelpText>Campo obligatorio en etapa=&apos;Preingreso&apos;</inlineHelpText>
        <label>Tipo de pago</label>
        <picklist>
            <picklistValues>
                <fullName>Cofinanciada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gratis</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tipo_de_tarifa__c</fullName>
        <inlineHelpText>Campo obligatorio en Etapa= &apos;Presentado Plan Personal&apos;</inlineHelpText>
        <label>Tipo de tarifa</label>
        <picklist>
            <picklistValues>
                <fullName>Diaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mensual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visita_realizada_en__c</fullName>
        <inlineHelpText>Campo obligatorio en Etapa= &apos;Visita Planificada&apos;</inlineHelpText>
        <label>Lugar de la visita</label>
        <picklist>
            <picklistValues>
                <fullName>Centro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lugar de residencia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centro Hospitalario</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Oportunidad</label>
    <nameField>
        <displayFormat>{YY}/{000000}</displayFormat>
        <label>Contador de Oportunidad</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Oportunidades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SAR Blai Sandbox/src/classes/Test_REST_WebService.cls
/** 
* File Name:   Test_REST_WebService
* Description: Classe test de la clase REST_WebService
* Copyright:   Konozca 
* @author:     Jose M Perez
* Modification Log 
**/ 

@isTest
public class Test_REST_WebService {
    static testMethod void myUnitTest() {
        //Crear Oportunidad
        Oportunidad_platform__c op = new Oportunidad_platform__c();        
        op.Etapa__c = 'Abierta';
        op.Canal__c = 'Llamada al Cat';
        op.Procedencia__c = 'Internet';
        op.Pagina_web__c = 'Google';
        op.Tipo_de_tarifa__c = 'Diaria';
        op.Tipo_de_pago__c = 'gratis';
        op.IBAN__c = 'ES9121000418450200051332';
        op.Regimen__c = 'UED';
        op.Tipo_de_Financiacion__c = 'Privado';
        op.Fecha_prevista_de_ingreso__c = Date.today();
        op.Fecha_finalizacion__c = System.today().addDays(15);
        op.Visita_realizada_en__c = 'Centro';
        op.Tipo_de_pago__c = 'Gratis';
        op.Precio_Colgantes__c = 10;
        op.Precio_sin_colgante__c = 5;
        op.Nombre_propio_y_plena_capacidad_de__c = true;
        op.Nombre_Avalista__c = 'sr avalista';
        triggerHelper.recursiveHelper3(true);                  
        insert op;          
        
        
        REST_WebService ws = new REST_WebService('user', 'pass');
        ws.GetDevices();
        Map<String, Object> p = new Map<String, Object>();
        p.put(REST_WebService.USER_VIDSIGNER, 'ac.userVidsigner__c');
        p.put(REST_WebService.PASS_VIDSIGNER, 'ac.passVidsigner__c');        
        p.put(REST_WebService.OP_ID , String.valueOf(op.id));
        p.put(REST_WebService.OP_NAME, op.Name);
        ws.postDocuments(p);
        
    }
}